import json
import re
import html

# Vietnamese tennis glossary
glossary = {
    # Core tennis terms
    "backhand slice": "trái tay slice",
    "slice": "slice",
    "backhand": "trái tay",
    "forehand": "thuận tay",
    "forehand slice": "thuận tay slice",
    "racquet": "vợt",
    "racquet head": "đầu vợt",
    "net": "lưới",
    "baseline": "vạch giao bóng",
    "court": "sân",
    "shot": "cú đánh",
    "stroke": "cú đánh",
    "volley": "volley",
    "grip": "cách cầm vợt",
    "follow-through": "đà hoàn thành",
    "backswing": "đường vợt lùi",
    "swing": "đường vợt",
    "contact point": "điểm tiếp xúc",
    "body": "cơ thể",
    "legs": "chân",
    "hips": "hông",
    "trunk": "thân",
    "arm": "cánh tay",
    "recreational tennis": "tennis giải trí",
    "offensive": "tấn công",
    "neutral": "trung lập",
    "power": "sức mạnh",
    "speed": "tốc độ",
    "bite": "độ cắn",
    "skid": "trượt",
    "penetration": "độ xuyên",
    "float": "nổi",
    "attack": "tấn công",
    "recovery": "phục hồi",
    "position": "vị trí",
    "master": "làm chủ",
    "buy yourself time": "giành thời gian",
    "push out": "bị đẩy ra",
    "engage": "sử dụng",
    "feel drill": "bài tập cảm nhận",
    "technique": "kỹ thuật",
    "engage your whole body": "sử dụng toàn bộ cơ thể",
    "energy sources": "nguồn năng lượng",
    "open stance": "tư thế mở",
    "closed stance": "tư thế đóng",
    "stance": "tư thế",
    "split-step": "split-step",
    "footwork": "di chuyển chân",
    "kinetic chain": "chuỗi động học",
    "ground reaction force": "lực phản ứng mặt đất",
    "topspin": "topspin",
    "flat": "bằng",
    "spin": "xoáy",
    "rotation": "xoay",
    "momentum": "động lượng",
    "racket head speed": "tốc độ đầu vợt",
    "non-dominant arm": "tay không đánh",
    "dominant arm": "tay đánh",
    "two-handed backhand": "trái tay hai tay",
    "one-handed backhand": "trái tay một tay",
    "open-stance backhand": "trái tay tư thế mở",
    "open stance backhand": "trái tay tư thế mở",
    "hip rotation": "xoay hông",
    "shoulder rotation": "xoay vai",
    "weight transfer": "chuyển trọng lượng",
    "unit rotation": "xoay thân",
    "coiling": "coil",
    "uncoiling": "un-coil",
    "loading": "tải trọng",
    "explosive": "bùng nổ",
    "balance": "thăng bằng",
    "recovery position": "tư thế phục hồi",
    "ready position": "tư thế sẵn sàng",
    "split step": "split-step",
    "first step": "bước đầu tiên",
    "direction": "hướng",
    "court position": "vị trí trên sân",
    "court coverage": "che kín sân",
    "defensive": "phòng thủ",
    "offensive shot": "cú tấn công",
    "offensive situation": "tình huống tấn công",
    "offensive stroke": "cú tấn công",
    "offensive shot selection": "lựa chọn cú tấn công",
    "sit up": "nổi lên",
    "floating slice": "slice nổi",
    "heavy skid": "trượt nặng",
    "low penetration": "độ xuyên thấp",
    "carving": "cắn",
    "cutting": "cắt",
    "cut": "cắt",
    "polishing technique": "kỹ thuật hoàn thiện",
    "drill": "bài tập",
    "alternate": "luân phiên",
    "long cut": "cú cắt dài",
    "straight line": "đường thẳng",
    "tape": "dải băng (lưới)",
    "slight": "nhẹ",
    "extra speed": "tốc độ thêm",
    "increase risk": "tăng rủi ro",
    "missing": "trượt bóng",
    "go lower": "đi thấp hơn",
    "travel faster": "di chuyển nhanh hơn",
    "actually apply": "thực sự áp dụng",
    "when": "khi nào",
    "apply for": "áp dụng cho",
    "comment": "bình luận",
    "below": "bên dưới",
    "extra": "thêm",
    "whole body": "toàn bộ cơ thể",
    "disengage": "không sử dụng",
    "too focused": "quá tập trung",
    "arm movement": "chuyển động cánh tay",
    "imagine": "tưởng tượng",
    "meter": "mét",
    "feet": "bàn chân",
    "straight": "thẳng",
    "stop touching": "ngừng chạm",
    "lift": "nâng lên",
    "only then": "chỉ sau đó",
    "change": "thay đổi",
    "path": "đường đi",
    "hit": "đánh",
    "engage your whole body": "sử dụng toàn bộ cơ thể",
    "push out of the court": "bị đẩy ra khỏi sân",
    "need to buy yourself time": "cần giành thời gian",
    "get back": "quay lại",
    "correct recovery position": "tư thế phục hồi đúng",
    "free": "tự do",
    "let me know": "cho tôi biết",
    "worked for you": "hiệu quả với bạn",
    "feel free": "hãy",
    "as I mentioned": "như tôi đã đề cập",
    "mentioned in the video": "đề cập trong video",
    "add bite": "thêm độ cắn",
    "whether": "dù là",
    "more offensive": "tấn công hơn",
    "simple": "đơn giản",
    "simple neutral shot": "cú đánh trung lập đơn giản",
    "from tape down": "từ dải băng xuống",
    "improve": "cải thiện",
    "most volleys": "hầu hết cú volley",
    "need to be hit": "cần được đánh",
    "with a slight slice": "với slice nhẹ",
    "note that": "lưu ý rằng",
    "you can use": "bạn có thể sử dụng",
    "this exercise": "bài tập này",
    "for your forehand slice": "cho cú thuận tay slice",
    "also improve": "cũng cải thiện",
    "will still take you some time": "vẫn sẽ mất một thời gian",
    "to master": "để làm chủ",
    "more offensive stroke": "cú tấn công hơn",
    "you will also need to learn": "bạn cũng cần học",
    "when to actually apply": "khi nào thực sự áp dụng",
    "that extra bite": "độ cắn thêm đó",
    "for more offensive situations": "cho các tình huống tấn công hơn",
    "or use": "hoặc sử dụng",
    "slower, floating slice": "slice chậm hơn, nổi",
    "when you're pushed": "khi bạn bị đẩy",
    "out of the court": "ra khỏi sân",
    "and need": "và cần",
    "to get back": "để quay lại",
    "in the correct recovery position": "vào tư thế phục hồi đúng",
    "feel free to let me know": "hãy cho tôi biết",
    "in the comments below": "trong bình luận bên dưới",
    "how this backhand slice tip worked for you": "mẹo trái tay slice này có hiệu quả với bạn như thế nào",
    "the feel exercise": "bài tập cảm nhận",
    "of cutting the net": "cắt lưới",
    "is one of": "là một trong",
    "the final polishing techniques": "các kỹ thuật hoàn thiện cuối cùng",
    "one needs to add": "cần thêm",
    "to one's tennis backhand slice technique": "vào kỹ thuật trái tay slice tennis",
    "in order to make": "để làm cho",
    "the slice more effective": "slice hiệu quả hơn",
    "and not sit up in the air": "và không nổi lên trên không",
    "imagine slicing": "tưởng tượng cắt",
    "the net open": "lưới mở",
    "with your backhand slice": "với cú trái tay slice",
    "as I mentioned in the video": "như tôi đã đề cập trong video",
    "to add bite to your slice backhand": "để thêm độ cắn vào trái tay slice",
    "you should": "bạn nên",
    "make a long cut": "thực hiện cú cắt dài",
    "imagine making": "tưởng tượng thực hiện",
    "a meter (3-4 feet) long slice": "cú cắt dài một mét (3-4 bàn chân)",
    "into the net": "vào lưới",
    "slice the net from tape down": "cắt lưới từ dải băng xuống",
    "don't change the racquet path": "không thay đổi đường vợt",
    "keep it in a straight line": "giữ nó trong đường thẳng",
    "until you stop touching the net": "cho đến khi bạn ngừng chạm lưới",
    "and only then": "và chỉ sau đó",
    "lift the racquet into the follow-through": "nâng vợt lên vào đà hoàn thành",
    "alternate between": "luân phiên giữa",
    "the feel drill of slicing the net": "bài tập cảm nhận cắt lưới",
    "and hitting backhand slice shots": "và đánh cú trái tay slice",
    "from the baseline": "từ vạch giao bóng",
    "accelerate a few times with full speed": "tăng tốc vài lần với tốc độ tối đa",
    "as that will help you": "vì điều đó sẽ giúp bạn",
    "engage your whole body into the shot": "sử dụng toàn bộ cơ thể vào cú đánh",
    "and feel": "và cảm nhận",
    "which parts of the body": "phần nào của cơ thể",
    "you can use to generate power": "bạn có thể sử dụng để tạo sức mạnh",
    "oftentimes": "thường thì",
    "players are too focused on their arm movement": "người chơi quá tập trung vào chuyển động cánh tay",
    "and thus disengage the legs": "và do đó không sử dụng chân",
    "the legs, hips and the trunk": "chân, hông và thân",
    "are the main energy sources": "là nguồn năng lượng chính",
    "for all shots": "cho tất cả các cú đánh",
    "including a backhand slice": "bao gồm cả trái tay slice",
    "note that you can use this exercise": "lưu ý rằng bạn có thể sử dụng bài tập này",
    "of cutting the net for your forehand slice": "cắt lưới cho cú thuận tay slice",
    "and it will also improve": "và nó cũng sẽ cải thiện",
    "the bite on your volleys": "độ cắn trên cú volley",
    "as most volleys need to be hit with a slight slice": "vì hầu hết cú volley cần được đánh với slice nhẹ",
    "of course": "tất nhiên",
    "with the extra speed of the racquet head": "với tốc độ thêm của đầu vợt",
    "you will increase the risk of missing": "bạn sẽ tăng rủi ro trượt bóng",
    "since the ball will go lower above the net": "vì bóng sẽ đi thấp hơn trên lưới",
    "and travel faster": "và di chuyển nhanh hơn",
    "therefore": "do đó",
    "it will still take you some time to master": "vẫn sẽ mất một thời gian để làm chủ",
    "the backhand slice shot as a more offensive stroke in tennis": "cú trái tay slice như một cú tấn công hơn trong tennis",
    "you will also need to learn when to actually apply": "bạn cũng cần học khi nào thực sự áp dụng",
    "that extra bite for more offensive situations": "độ cắn thêm đó cho các tình huống tấn công hơn",
    "or use a slower, floating slice": "hoặc sử dụng slice chậm hơn, nổi",
    "when you're pushed out of the court": "khi bạn bị đẩy ra khỏi sân",
    "and need to buy yourself time": "và cần giành thời gian",
    "to get back in the correct recovery position": "để quay lại tư thế phục hồi đúng",
    "feel free to let me know in the comments below": "hãy cho tôi biết trong bình luận bên dưới",
    "how this backhand slice tip worked for you": "mẹo trái tay slice này có hiệu quả với bạn như thế nào",
    "the feel exercise of cutting the net": "bài tập cảm nhận cắt lưới",
    "is one of the final polishing techniques": "là một trong những kỹ thuật hoàn thiện cuối cùng",
    "one needs to add to one's tennis backhand slice technique": "cần thêm vào kỹ thuật trái tay slice tennis",
    "in order to make the slice more effective": "để làm cho slice hiệu quả hơn",
    "and not sit up in the air": "và không nổi lên trên không",
    "imagine slicing the net open with your backhand slice": "tưởng tượng cắt lưới mở với cú trái tay slice",
    "as I mentioned in the video": "như tôi đã đề cập trong video",
    "to add bite to your slice backhand": "để thêm độ cắn vào trái tay slice",
    "you should": "bạn nên",
    "make a long cut": "thực hiện cú cắt dài",
    "imagine making a meter (3-4 feet) long slice into the net": "tưởng tượng thực hiện cú cắt dài một mét (3-4 bàn chân) vào lưới",
    "slice the net from tape down": "cắt lưới từ dải băng xuống",
    "don't change the racquet path": "không thay đổi đường vợt",
    "keep it in a straight line until you stop touching the net": "giữ nó trong đường thẳng cho đến khi bạn ngừng chạm lưới",
    "and only then lift the racquet into the follow-through": "và chỉ sau đó nâng vợt lên vào đà hoàn thành",
    "alternate between the feel drill of slicing the net": "luân phiên giữa bài tập cảm nhận cắt lưới",
    "and hitting backhand slice shots from the baseline": "và đánh cú trái tay slice từ vạch giao bóng",
    "accelerate a few times with full speed": "tăng tốc vài lần với tốc độ tối đa",
    "as that will help you engage your whole body into the shot": "vì điều đó sẽ giúp bạn sử dụng toàn bộ cơ thể vào cú đánh",
    "and feel which parts of the body you can use to generate power": "và cảm nhận phần nào của cơ thể bạn có thể sử dụng để tạo sức mạnh",
    "oftentimes, players are too focused on their arm movement and thus disengage the legs": "thường thì người chơi quá tập trung vào chuyển động cánh tay và do đó không sử dụng chân",
    "the legs, hips and the trunk are the main energy sources for all shots including a backhand slice": "chân, hông và thân là nguồn năng lượng chính cho tất cả các cú đánh bao gồm cả trái tay slice",
    "note that you can use this exercise of cutting the net for your forehand slice": "lưu ý rằng bạn có thể sử dụng bài tập cắt lưới này cho cú thuận tay slice",
    "and it will also improve the bite on your volleys as most volleys need to be hit with a slight slice": "và nó cũng sẽ cải thiện độ cắn trên cú volley vì hầu hết cú volley cần được đánh với slice nhẹ",
    "of course, with the extra speed of the racquet head, you will increase the risk of missing": "tất nhiên, với tốc độ thêm của đầu vợt, bạn sẽ tăng rủi ro trượt bóng",
    "since the ball will go lower above the net and travel faster": "vì bóng sẽ đi thấp hơn trên lưới và di chuyển nhanh hơn",
    "therefore, it will still take you some time to master the backhand slice shot as a more offensive stroke in tennis": "do đó, vẫn sẽ mất một thời gian để làm chủ cú trái tay slice như một cú tấn công hơn trong tennis",
    "you will also need to learn when to actually apply that extra bite for more offensive situations": "bạn cũng cần học khi nào thực sự áp dụng độ cắn thêm đó cho các tình huống tấn công hơn",
    "or use a slower, floating slice when you're pushed out of the court and need to buy yourself time to get back in the correct recovery position": "hoặc sử dụng slice chậm hơn, nổi khi bạn bị đẩy ra khỏi sân và cần giành thời gian để quay lại tư thế phục hồi đúng",
    "feel free to let me know in the comments below how this backhand slice tip worked for you": "hãy cho tôi biết trong bình luận bên dưới mẹo trái tay slice này có hiệu quả với bạn như thế nào",
    "the backhand slice is one of the most common shots in recreational tennis, yet in most cases the slice is floating up too high and is easy to attack": "trái tay slice là một trong những cú đánh phổ biến nhất trong tennis giải trí, nhưng trong hầu hết các trường hợp slice nổi lên quá cao và dễ bị tấn công",
    "the following backhand slice tip helps you develop that extra bite on the slice (whether backhand or forehand) and change the slice from a simple neutral shot to a more offensive one": "mẹo trái tay slice sau đây giúp bạn phát triển độ cắn thêm trên slice (dù là trái tay hay thuận tay) và thay đổi slice từ một cú đánh trung lập đơn giản thành mộc cú tấn công hơn",
    "the biting backhand slice": "trái tay slice cắn mạnh",
    "the feel exercise of cutting the net is one of the final polishing techniques one needs to add to one's tennis backhand slice technique in order to make the slice more effective and not sit up in the air": "bài tập cảm nhận cắt lưới là một trong những kỹ thuật hoàn thiện cuối cùng cần thêm vào kỹ thuật trái tay slice tennis để làm cho slice hiệu quả hơn và không nổi lên trên không",
    "imagine slicing the net open with your backhand slice": "tưởng tượng cắt lưới mở với cú trái tay slice",
    "as I mentioned in the video, to add bite to your slice backhand, you should": "như tôi đã đề cập trong video, để thêm độ cắn vào trái tay slice, bạn nên",
    "make a long cut – imagine making a meter (3–4 feet) long slice into the net": "thực hiện cú cắt dài – tưởng tượng thực hiện cú cắt dài một mét (3-4 bàn chân) vào lưới",
    "slice the net from tape down and don't change the racquet path – keep it in a straight line until you stop touching the net and only then lift the racquet into the follow-through": "cắt lưới từ dải băng xuống và không thay đổi đường vợt – giữ nó trong đường thẳng cho đến khi bạn ngừng chạm lưới và chỉ sau đó nâng vợt lên vào đà hoàn thành",
    "alternate between the feel drill of slicing the net and hitting backhand slice shots from the baseline": "luân phiên giữa bài tập cảm nhận cắt lưới và đánh cú trái tay slice từ vạch giao bóng",
    "accelerate a few times with full speed as that will help you engage your whole body into the shot and feel which parts of the body you can use to generate power": "tăng tốc vài lần với tốc độ tối đa vì điều đó sẽ giúp bạn sử dụng toàn bộ cơ thể vào cú đánh và cảm nhận phần nào của cơ thể bạn có thể sử dụng để tạo sức mạnh",
    "oftentimes, players are too focused on their arm movement and thus disengage the legs": "thường thì người chơi quá tập trung vào chuyển động cánh tay và do đó không sử dụng chân",
    "the legs, hips and the trunk are the main energy sources for all shots including a backhand slice": "chân, hông và thân là nguồn năng lượng chính cho tất cả các cú đánh bao gồm cả trái tay slice",
    "note that you can use this exercise of cutting the net for your forehand slice, and it will also improve the bite on your volleys as most volleys need to be hit with a slight slice": "lưu ý rằng bạn có thể sử dụng bài tập cắt lưới này cho cú thuận tay slice, và nó cũng sẽ cải thiện độ cắn trên cú volley vì hầu hết cú volley cần được đánh với slice nhẹ",
    "of course, with the extra speed of the racquet head, you will increase the risk of missing since the ball will go lower above the net and travel faster": "tất nhiên, với tốc độ thêm của đầu vợt, bạn sẽ tăng rủi ro trượt bóng vì bóng sẽ đi thấp hơn trên lưới và di chuyển nhanh hơn",
    "therefore, it will still take you some time to master the backhand slice shot as a more offensive stroke in tennis": "do đó, vẫn sẽ mất một thời gian để làm chủ cú trái tay slice như một cú tấn công hơn trong tennis",
    "you will also need to learn when to actually apply that extra bite for more offensive situations or use a slower, floating slice when you're pushed out of the court and need to buy yourself time to get back in the correct recovery position": "bạn cũng cần học khi nào thực sự áp dụng độ cắn thêm đó cho các tình huống tấn công hơn hoặc sử dụng slice chậm hơn, nổi khi bạn bị đẩy ra khỏi sân và cần giành thời gian để quay lại tư thế phục hồi đúng",
    "feel free to let me know in the comments below how this backhand slice tip worked for you": "hãy cho tôi biết trong bình luận bên dưới mẹo trái tay slice này có hiệu quả với bạn như thế nào",
}

def translate_text(text):
    """Translate English text to Vietnamese using glossary."""
    # Sort by length (longest first) to match multi-word phrases first
    sorted_terms = sorted(glossary.keys(), key=len, reverse=True)
    
    result = text
    for term in sorted_terms:
        vn_term = glossary[term]
        # Use word boundary matching for whole words
        pattern = r'\b' + re.escape(term) + r'\b'
        result = re.sub(pattern, vn_term, result, flags=re.IGNORECASE)
    
    return result

def translate_article(html_content):
    """Translate HTML article content while preserving HTML tags."""
    # Split by HTML tags and translate only the text between tags
    parts = re.split(r'(<[^>]+>)', html_content)
    translated_parts = []
    
    for part in parts:
        if part.startswith('<'):
            # HTML tag - keep as is
            translated_parts.append(part)
        else:
            # Text content - translate
            if part.strip():
                translated = translate_text(part)
                translated_parts.append(translated)
            else:
                translated_parts.append(part)
    
    return ''.join(translated_parts)

# Read batch file
with open('_batch_0.json', 'r', encoding='utf-8') as f:
    batch = json.load(f)

for article in batch:
    section = article['section']
    slug = article['slug']
    en_html = article['en_article']
    
    # Translate
    vi_html = translate_article(en_html)
    
    # Write output
    filename = f'{section}_{slug}.vi.md'
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(vi_html)
    
    print(f'Wrote: {filename}')
