# -*- coding: utf-8 -*-
"""
Builds tennis_glossary_vi.json + regenerates glossary.html for the
Tennis Unified Vietnamese digital library.

Dataset authored from a corpus sweep of all 97 book articles in vi/books/.
Categories: biomechanics, strokes, tactics, doubles, footwork_movement,
mental_psychology, training_conditioning, equipment_scoring, injuries_medical,
rules_officiating, surfaces_conditions, player_archetypes, stats_analytics.
"""
import json, io, os

C = {
    "biomechanics": "Sinh Cơ Học",
    "strokes": "Kỹ Thuật Cú Đánh",
    "tactics": "Chiến Thuật",
    "doubles": "Đánh Đôi",
    "footwork_movement": "Di Chuyển & Bước Chân",
    "mental_psychology": "Tâm Lý Thi Đấu",
    "training_conditioning": "Huấn Luyện & Thể Lực",
    "equipment_scoring": "Dụng Cụ & Luật Tính Điểm",
    "injuries_medical": "Chấn Thương & Y Học Thể Thao",
    "rules_officiating": "Luật & Trọng Tài",
    "surfaces_conditions": "Mặt Sân & Điều Kiện",
    "player_archetypes": "Mẫu Hình Người Chơi",
    "stats_analytics": "Thống Kê & Phân Tích",
}

# (id, en, vi, [variants], category, note, [source_book_keys])
T = [
# ───────────────────────────── BIOMECHANICS ─────────────────────────────
("kinetic_chain", "Kinetic Chain", "Chuỗi động học liên hoàn",
 ["chuỗi động lực", "dây chuyền động lực", "chuỗi vận động"], "biomechanics",
 "Trình tự truyền lực từ chân → hông → thân → vai → tay → vợt.", ["biomechanics", "tennis_anatomy", "wave_transmission"]),
("kinetic_energy_transfer", "Energy Transfer / Summation of Speed", "Cộng dồn tốc độ theo chuỗi",
 ["cộng lực tuần tự", "tổng hợp tốc độ"], "biomechanics",
 "Nguyên lý mỗi khớp truyền và khuếch đại tốc độ cho khớp tiếp theo trong chuỗi động học.", ["biomechanics", "wave_transmission"]),
("proximal_to_distal", "Proximal-to-Distal Sequencing", "Trình tự từ gốc tới ngọn chi",
 ["trình tự gần-xa", "tuần tự gốc ngọn"], "biomechanics",
 "Các đốt xa cơ thể (bàn tay, vợt) đạt tốc độ cao nhất sau cùng và muộn nhất, tạo hiệu ứng roi da.", ["biomechanics", "tennis_science"]),
("summation_of_forces", "Summation of Forces", "Cộng dồn lực",
 ["cộng lực", "tổng lực"], "biomechanics",
 "Việc huy động đồng thời nhiều nhóm cơ và khớp để tạo lực lớn hơn bất kỳ bộ phận đơn lẻ nào.", ["biomechanics", "tennis_anatomy"]),
("stretch_shortening_cycle", "Stretch-Shortening Cycle (SSC)", "Chu kỳ căng–co rút (SSC)",
 ["chu kỳ căng co", "vòng kéo giãn rút ngắn"], "biomechanics",
 "Cơ được kéo giãn nhanh ngay trước khi co lại giúp lưu trữ năng lượng đàn hồi và tăng lực đẩy.", ["biomechanics", "tennis_anatomy", "maximum_tennis"]),
("elastic_energy", "Elastic Energy", "Năng lượng đàn hồi",
 ["năng lượng đàn hồi", "năng lượng tích trữ"], "biomechanics",
 "Năng lượng dự trữ trong gân và cân mạc khi cơ bị kéo căng, giải phóng trong pha tăng tốc.", ["wave_transmission", "tennis_anatomy"]),
("coil", "Coil (Wind-up / Loading)", "Lên dây cót (tích lực)",
 ["cuộn người", "tích lực", "vặn người"], "biomechanics",
 "Pha xoay thân trên tạo thế đối kháng, dự trữ năng lượng đàn hồi trước khi bung cú đánh.", ["art_modern_tennis", "maximum_tennis", "paradigm_shift"]),
("uncoil", "Uncoil (Release)", "Bung xoay (giải phóng)",
 ["bung người", "mở xoay"], "biomechanics",
 "Pha giải phóng xoay theo chiều ngược lại của coil, đưa năng lượng dự trữ vào cú đánh.", ["art_modern_tennis", "maximum_tennis"]),
("hip_shoulder_separation", "Hip–Shoulder Separation / X-Factor", "Tách xoay hông–vai (X-Factor)",
 ["x-factor", "tách hông vai"], "biomechanics",
 "Chênh lệch góc xoay giữa hông và vai trong pha lấy đà; tăng tách xoay (tới ngưỡng hợp lý) tăng tốc độ đầu vợt.", ["biomechanics", "tennis_anatomy"]),
("trunk_rotation", "Trunk (Torso) Rotation", "Xoay thân mình",
 ["xoay thân", "xoay torso"], "biomechanics",
 "Góc xoay của thân trên quanh trục dọc, cầu nối giữa hông và vai trong chuỗi động học.", ["tennis_anatomy", "biomechanics"]),
("unit_turn", "Unit Turn", "Xoay nguyên khối thân trên",
 ["xoay đơn vị", "xoay khối người", "xoay vai-hông đồng bộ"], "biomechanics",
 "Vai, hông và chân xoay đồng bộ như một khối ngay khi nhận diện hướng bóng.", ["art_modern_tennis", "bollettieri"]),
("external_shoulder_rotation", "External Shoulder Rotation", "Xoay ngoài khớp vai",
 ["xoay vai ra ngoài", "lên dây cót vai"], "biomechanics",
 "Giai đoạn 'lên dây cót' (loading) trước khi xoay trong khớp vai; cánh tay xoay ra sau và ngoài.", ["biomechanics", "tennis_anatomy"]),
("internal_shoulder_rotation", "Internal Shoulder Rotation", "Xoay trong khớp vai",
 ["xoay vai vào trong", "vặn vai trong"], "biomechanics",
 "Chuyển động chính tạo tốc độ đầu vợt trong pha tăng tốc của cú giao bóng.", ["biomechanics", "tennis_anatomy"]),
("pronation", "Pronation", "Động tác sấp cổ tay / xoay trong cẳng tay",
 ["gập cổ tay", "sấp tay", "xoay sấp"], "biomechanics",
 "Xoay xương quay quanh xương trụ, thường thấy ở pha tiếp xúc bóng của cú giao bóng và forehand hiện đại.", ["biomechanics", "art_modern_tennis"]),
("supination", "Supination", "Động tác ngửa cẳng tay",
 ["ngửa tay", "xoay ngửa"], "biomechanics",
 "Xoay cẳng tay sao cho lòng bàn tay hướng lên; thường xuất hiện trong pha chuẩn bị của backhand một tay.", ["biomechanics"]),
("racquet_lag", "Racquet Lag / Drag", "Độ trễ vợt",
 ["vợt kéo theo", "vợt trễ sau tay", "lag"], "biomechanics",
 "Đầu vợt rơi ra sau và dưới bàn tay rồi 'bật' về trước ở pha tăng tốc, tạo tốc độ đầu vợt mà không gồng cơ.", ["art_modern_tennis", "maximum_tennis"]),
("wrist_snap", "Wrist Snap", "Bật cổ tay",
 ["gập cổ tay nhanh", "búng cổ tay"], "biomechanics",
 "Động tác gập cổ tay nhanh ở thời điểm tiếp xúc, góp phần tăng tốc độ đầu vợt (đặc biệt ở giao bóng và smash).", ["bollettieri", "high_tech_tennis"]),
("leg_drive", "Leg Drive", "Lực đạp chân",
 ["đạp chân", "bật chân"], "biomechanics",
 "Lực đẩy từ hai chân hướng lên và ra trước, khởi nguồn cho chuỗi động học của giao bóng và cú đánh.", ["biomechanics", "tennis_anatomy"]),
("ground_reaction_force", "Ground Reaction Force (GRF)", "Lực phản lực từ mặt đất",
 ["phản lực nền", "lực đẩy từ sàn"], "biomechanics",
 "Lực mặt sân tác động ngược lại cơ thể khi đạp chân, là nguồn lực khởi phát của chuỗi động học.", ["biomechanics", "tennis_science"]),
("knee_bend", "Knee Bend (Flexion)", "Gập gối",
 ["khuỵu gối", "gập đầu gối"], "biomechanics",
 "Độ gập gối trong pha chuẩn bị; quyết định độ sâu trọng tâm và khả năng tích lực đàn hồi.", ["biomechanics", "bollettieri"]),
("racquet_head_speed", "Racquet Head Speed (RHS)", "Tốc độ đầu vợt",
 ["tốc độ mặt vợt", "vận tốc vợt", "tốc độ vợt"], "biomechanics",
 "Tốc độ di chuyển của đầu vợt tại thời điểm tiếp xúc bóng, yếu tố quyết định tốc độ bóng đi.", ["high_tech_tennis", "art_modern_tennis"]),
("center_of_gravity", "Center of Gravity / Balance", "Trọng tâm cơ thể",
 ["tâm trọng lực", "thăng bằng"], "biomechanics",
 "Vị trí trọng tâm ảnh hưởng trực tiếp đến thăng bằng và khả năng tạo lực.", ["biomechanics", "bollettieri"]),
("proprioception", "Proprioception", "Cảm nhận bản thể",
 ["cảm giác cơ thể", "nhận thức vị trí cơ thể"], "biomechanics",
 "Khả năng cảm nhận vị trí và chuyển động của cơ thể/vợt mà không cần nhìn.", ["tennis_anatomy", "tennis_medicine"]),
("fascia_sling_system", "Fascia / Sling System", "Hệ thống dây chằng chéo cân mạc",
 ["hệ thống sling cơ", "chuỗi cơ chéo", "chuỗi cân mạc"], "biomechanics",
 "Mạng lưới cân mạc kết nối các nhóm cơ chéo (ví dụ: sling sau chéo vai-hông đối diện) hỗ trợ truyền lực xoay.", ["muscle_slings", "tennis_anatomy"]),
("loading_phase", "Loading Phase", "Giai đoạn nạp lực",
 ["giai đoạn dồn lực", "pha tích lũy năng lượng", "nạp lực"], "biomechanics",
 "Giai đoạn dồn trọng tâm và kéo giãn cơ trước khi bung lực (ví dụ: gối khuỵu trước khi bật nhảy giao bóng).", ["biomechanics", "bollettieri"]),
("separation_angle", "Separation Angle (Shoulder–Hip)", "Góc tách vai–hông",
 ["góc tách", "góc xoay thân"], "biomechanics",
 "Góc chênh giữa đường vai và đường hông tại thời điểm chuẩn bị cú đánh; đại lượng đo lường mức độ tích lực xoay.", ["biomechanics"]),

# ───────────────────────────── STROKES ─────────────────────────────
("forehand", "Forehand", "Cú thuận tay (forehand)",
 ["cú phải", "đánh thuận tay"], "strokes",
 "Cú đánh bóng ở phía tay thuận, thực hiện sau khi bóng nảy một lần trong sân.", ["bollettieri", "art_modern_tennis", "laver"]),
("backhand", "Backhand", "Cú trái tay (backhand)",
 ["cú trái", "đánh trái tay"], "strokes",
 "Cú đánh bóng ở phía tay không thuận; có thể đánh một tay hoặc hai tay.", ["bollettieri", "art_modern_tennis", "laver"]),
("groundstroke", "Groundstroke", "Cú đánh nền (groundstroke)",
 ["cú cuối sân", "cú đánh từ nền sân"], "strokes",
 "Cú đánh thực hiện sau khi bóng nảy một lần, từ khu vực cuối sân; gồm forehand và backhand.", ["strokes_strategies", "competitive_tennis"]),
("one_handed_backhand", "One-Handed Backhand", "Trái tay một tay",
 ["backhand một tay", "trái tay 1 tay"], "strokes",
 "Trái tay thực hiện chỉ bằng tay thuận; đòi hỏi chuẩn bị sớm và ổn định cổ tay, mạnh ở bóng thấp và slice.", ["strokes_of_genius", "art_modern_tennis"]),
("two_handed_backhand", "Two-Handed Backhand", "Trái tay hai tay",
 ["backhand hai tay", "trái tay 2 tay"], "strokes",
 "Trái tay với cả hai tay trên cán vợt; phổ biến ở quần vợt hiện đại nhờ ổn định và tạo topspin tốt hơn.", ["bollettieri", "strokes_of_genius"]),
("takeback", "Takeback / Backswing", "Vung vợt ra sau (lấy đà)",
 ["vung ra sau", "lấy đà", "backswing"], "strokes",
 "Pha đưa vợt ra sau và lên để chuẩn bị cho cú đánh; độ dài backswing quyết định độ dài đường vợt.", ["strokes_strategies", "art_modern_tennis"]),
("compact_backswing", "Compact Backswing", "Vung vợt ra sau gọn",
 ["lấy đà ngắn", "backswing gọn"], "strokes",
 "Backswing ngắn nhờ xoay thân thay vì dùng tay, giúp đón bóng sớm và phòng ngự tốt hơn khi bị ép.", ["art_modern_tennis", "paradigm_shift"]),
("loop_backswing", "Loop Backswing", "Vung vợt ra sau theo vòng",
 ["lấy đà vòng cung", "vung vòng"], "strokes",
 "Đường vợt đi theo quỹ đạo vòng tròn từ dưới lên, tạo đà cho topspin ở forehand hiện đại.", ["bollettieri", "topspin"]),
("forward_swing", "Forward Swing", "Vung vợt tới trước",
 ["vung tới", "pha tăng tốc"], "strokes",
 "Pha vợt tăng tốc từ sau ra trước về phía bóng; nơi tốc độ đầu vợt đạt cực đại.", ["strokes_strategies", "biomechanics"]),
("contact_point", "Contact Point", "Điểm tiếp xúc bóng",
 ["điểm chạm bóng", "điểm va chạm"], "strokes",
 "Vị trí không gian nơi mặt vợt gặp bóng.", ["bollettieri", "art_modern_tennis"]),
("strike_zone", "Strike Zone", "Vùng đánh bóng lý tưởng",
 ["vùng đánh tối ưu", "vùng tiếp xúc"], "strokes",
 "Khoảng không gian (chiều cao, khoảng cách) mà người chơi tạo lực và kiểm soát tốt nhất.", ["bollettieri", "art_modern_tennis"]),
("follow_through", "Follow-Through", "Kết thúc cú đánh",
 ["kết thúc", "theo vợt sau tiếp xúc"], "strokes",
 "Pha vợt tiếp tục đi sau khi bóng rời mặt vợt; ảnh hưởng lớn đến kiểm soát và độ xoáy.", ["strokes_strategies", "laver"]),
("wiper_finish", "Windshield Wiper Finish", "Kết thúc kiểu cần gạt nước",
 ["vung vợt kiểu gạt mưa", "kết thúc xoay tròn", "wiper finish"], "strokes",
 "Kiểu kết thúc cú forehand hiện đại, cánh tay quét vòng cung ngang tạo topspin cao.", ["art_modern_tennis", "high_tech_tennis"]),
("reverse_forehand", "Reverse Forehand / Buggy Whip", "Forehand ngược (buggy whip)",
 ["buggy whip", "forehand vòng ngược"], "strokes",
 "Kiểu forehand kết thúc bằng cách đưa vợt vòng qua trên vai cùng bên, dùng khi bóng cao hoặc bị ép.", ["art_modern_tennis", "strokes_of_genius"]),
("topspin", "Topspin", "Xoáy lên",
 ["xoáy thuận", "xoáy trên"], "strokes",
 "Bóng xoáy theo chiều tiến, tạo quỹ đạo vòng cung và nảy cao.", ["topspin", "art_modern_tennis"]),
("backspin_slice", "Backspin / Underspin (Slice)", "Xoáy ngược (slice)",
 ["xoáy dưới", "underspin", "slice"], "strokes",
 "Bóng xoáy ngược chiều tiến, quỹ đạo thấp, nảy thấp và trượt.", ["strokes_strategies", "laver"]),
("sidespin", "Sidespin", "Xoáy ngang",
 ["xoáy cạnh", "xoáy bên"], "strokes",
 "Bóng xoáy quanh trục đứng, khiến bóng cong sang bên khi bay và nảy lệch khi chạm sân.", ["high_tech_tennis", "topspin"]),
("flat_shot", "Flat Shot", "Cú đánh phẳng",
 ["đánh phẳng", "bóng phẳng"], "strokes",
 "Cú đánh với rất ít xoáy lên hoặc xuống, quỹ đạo thấp và nhanh, biên an toàn nhỏ.", ["strokes_strategies", "tennis_2000"]),
("drive", "Drive", "Cú đánh thẳng (drive)",
 ["cú drive", "đánh mạnh phẳng"], "strokes",
 "Cú đánh nền mạnh, phẳng và sâu với tốc độ cao; nền tảng của lối chơi tấn công cuối sân.", ["how_to_play_winning", "strokes_strategies"]),
("on_the_rise", "On the Rise / Taking the Ball Early", "Đón bóng sớm (khi bóng đang lên)",
 ["đánh bóng nổi lên", "đón bóng sớm", "take the ball early"], "strokes",
 "Đánh bóng ngay sau khi nảy, ở giai đoạn bóng còn đang đi lên; rút ngắn thời gian của đối thủ.", ["art_modern_tennis", "paradigm_shift"]),
("half_volley", "Half-Volley", "Nửa vô-lê",
 ["vô lê nửa nảy", "bán vô-lê"], "strokes",
 "Đánh bóng ngay sau khi bóng vừa nảy chạm đất; kỹ thuật khó, thường dùng khi bị ép ở gần lưới.", ["bollettieri", "laver"]),
("volley", "Volley", "Cú vô-lê",
 ["đánh không nảy", "vô-lê"], "strokes",
 "Đánh bóng trước khi bóng chạm đất, thường thực hiện gần lưới.", ["bollettieri", "modern_volley"]),
("punch_volley", "Punch Volley", "Vô-lê đấm",
 ["vô lê đấm", "volley dứt khoát"], "strokes",
 "Vô-lê với động tác đẩy ngắn, dứt khoát, ít backswing, đưa bóng sâu và đặt đối thủ vào thế khó.", ["modern_volley", "laver"]),
("block_volley", "Block Volley", "Vô-lê chặn",
 ["volley chặn", "chặn bóng"], "strokes",
 "Vô-lê chỉ đặt mặt vợt đón bóng, hấp thụ lực, dùng khi đối mặt bóng quá nhanh để vung vợt.", ["modern_volley", "doubles_modern"]),
("drop_volley", "Drop Volley", "Vô-lê bỏ nhỏ",
 ["volley thả bóng", "vô lê bỏ nhỏ"], "strokes",
 "Vô-lê nhẹ, kết hợp hấp thụ lực, đưa bóng rơi ngay sau lưới bên đối phương.", ["modern_volley", "art_of_doubles"]),
("swinging_volley", "Swinging Volley", "Vô-lê vung (đánh xoáy)",
 ["volley vung", "vô lê tấn công"], "strokes",
 "Vô-lê thực hiện với đường vung đầy đủ như groundstroke, dùng để kết thúc điểm khi bóng bổng tới gần lưới.", ["modern_volley", "art_modern_tennis"]),
("lob_volley", "Lob Volley", "Vô-lê lốp",
 ["volley lốp", "vô lê lốp bóng"], "strokes",
 "Vô-lê mở mặt vợt đưa bóng bay cao qua đầu đối thủ đang áp sát lưới.", ["modern_volley", "art_of_doubles"]),
("overhead_smash", "Overhead Smash", "Cú đập trên đầu (smash)",
 ["smash", "đập bóng trên đầu", "cú đập"], "strokes",
 "Cú đánh từ trên cao xuống khi bóng bay qua đầu, thường được dùng để kết thúc điểm tại lưới.", ["bollettieri", "laver"]),
("scissors_kick", "Scissors Kick / Scissor Kick", "Động tác kéo cắt (scissors kick)",
 ["đá kéo cắt", "bật chân kiểu cắt kéo"], "strokes",
 "Động tác bật nhảy và hoán đổi hai chân khi smash trên cao, giúp đưa thân người ra sau và ổn định lực đập.", ["bollettieri", "sports_science"]),
("kick_serve", "Kick Serve (Topspin Serve)", "Giao bóng xoáy bật cao (kick serve)",
 ["giao bóng xoáy lên", "giao bóng nảy cao", "kick serve"], "strokes",
 "Cú giao bóng xoáy hỗn hợp topspin-sidespin khiến bóng nảy cao bất thường, dùng phổ biến cho giao bóng hai.", ["bollettieri", "laver"]),
("flat_serve", "Flat Serve", "Giao bóng phẳng (flat serve)",
 ["giao bóng thẳng", "giao bóng không xoáy"], "strokes",
 "Cú giao bóng tối đa tốc độ, ít xoáy; thường dùng cho giao bóng một.", ["bollettieri", "laver"]),
("slice_serve", "Slice Serve", "Giao bóng xoáy ngang (slice serve)",
 ["giao bóng cắt ngang", "giao bóng xoáy cạnh"], "strokes",
 "Cú giao bóng xoáy cạnh khiến bóng đi vòng cung ngang và kéo đối thủ ra khỏi sân.", ["bollettieri", "laver"]),
("american_twist", "American Twist Serve", "Giao bóng xoáy Mỹ (American twist)",
 ["giao bóng xoáy twist", "twist serve"], "strokes",
 "Biến thể kick serve với xoáy ngang và xoáy lên mạnh, bóng nảy cao và văng sang trái người nhận (với người tay phải).", ["bollettieri", "laver"]),
("body_serve", "Body Serve", "Giao bóng vào người",
 ["giao bóng nhắm người", "body serve"], "strokes",
 "Giao bóng nhắm trực diện vào thân người nhận, hạn chế biên độ vung vợt và gây bí.", ["doubles_strategy", "tennis_tactics"]),
("wide_serve", "Wide Serve", "Giao bóng biên rộng",
 ["giao bóng ra biên", "serve rộng"], "strokes",
 "Giao bóng hướng ra sát đường biên dọc, kéo người nhận ra khỏi sân và mở toang khoảng trống.", ["tennis_tactics", "doubles_strategy"]),
("t_serve", "T-Serve", "Giao bóng vào chữ T",
 ["giao bóng giữa sân", "giao bóng chữ T"], "strokes",
 "Giao bóng nhắm vào điểm giao của đường giữa và đường giao bóng, khóa góc trả bóng của đối thủ.", ["tennis_tactics", "laver"]),
("second_serve", "Second Serve", "Giao bóng hai",
 ["giao bóng lần hai", "serve 2"], "strokes",
 "Cú giao bóng sau khi giao bóng một hỏng; thường chú trọng xoáy và độ an toàn hơn tốc độ.", ["tennis_tactics", "doubles_strategy"]),
("serve_toss", "Toss", "Tung bóng",
 ["tung bóng giao", "ném bóng lên"], "strokes",
 "Hành động tung bóng lên trước khi giao; vị trí và độ cao tung quyết định loại giao bóng và độ ổn định.", ["bollettieri", "laver"]),
("trophy_pose", "Trophy Pose", "Tư thế cúp vàng (trophy)",
 ["thế trophy", "tư thế lên dây cót giao bóng"], "strokes",
 "Tư thế hai tay nâng cao, khuỷu gập, vai xoay ngoài hoàn toàn ở đỉnh của pha lấy đà giao bóng.", ["bollettieri", "art_modern_tennis"]),
("racquet_drop", "Racquet Drop", "Hạ vợt sau lưng (racquet drop)",
 ["hạ vợt", "vợt rơi sau lưng", "racket drop"], "strokes",
 "Pha đầu vợt hạ thấp xuống sau lưng trong giao bóng, tạo biên độ cho chuỗi tăng tốc.", ["bollettieri", "biomechanics"]),
("return_of_serve", "Return of Serve", "Trả giao bóng",
 ["đỡ giao bóng", "trả bóng giao"], "strokes",
 "Cú đánh đón giao bóng của đối thủ; là cú đánh quan trọng thứ hai sau giao bóng.", ["return_of_serve", "laver"]),
("block_return", "Block Return", "Trả giao bóng chặn",
 ["đỡ giao bóng chặn", "trả bóng block"], "strokes",
 "Kỹ thuật trả giao bóng bằng cách đặt mặt vợt đón bóng, dùng khi đối mặt giao bóng tốc độ cao.", ["return_of_serve", "tennis_tactics"]),
("chip_return", "Chip Return", "Trả giao bóng cắt (chip)",
 ["đỡ giao bóng cắt", "chip return"], "strokes",
 "Trả giao bóng bằng cú slice ngắn, bóng thấp; thường dùng để lên lưới hoặc phá nhịp đối thủ.", ["doubles_strategy", "return_of_serve"]),
("drop_shot", "Drop Shot", "Cú bỏ nhỏ (drop shot)",
 ["cú thả bóng", "bỏ nhỏ"], "strokes",
 "Cú đánh nhẹ, ít lực, bóng rơi ngay sau lưới đối phương.", ["art_of_doubles", "tennis_tactics"]),
("lob", "Lob", "Cú lốp bóng (lob)",
 ["lốp bóng", "bóng bổng"], "strokes",
 "Đánh bóng bay cao qua đầu đối thủ, thường dùng để phòng thủ hoặc phá thế lưới.", ["art_of_doubles", "doubles_strategy"]),
("defensive_lob", "Defensive Lob", "Lốp phòng ngự",
 ["lốp thủ", "lốp cứu bóng"], "strokes",
 "Lốp cao, sâu thực hiện khi bị ép, nhằm mua thời gian hồi vị và đẩy đối thủ ra khỏi lưới.", ["art_of_doubles", "doubles_strategy"]),
("offensive_lob", "Offensive Lob", "Lốp tấn công",
 ["lốp công", "lốp qua đầu"], "strokes",
 "Lốp chính xác và có kiểm soát nhằm kết thúc điểm hoặc buộc đối thủ ở lưới phải lùi lại.", ["art_of_doubles", "doubles_strategy"]),
("topspin_lob", "Topspin Lob", "Lốp xoáy lên",
 ["lốp topspin", "lốp xoáy"], "strokes",
 "Lốp với xoáy lên mạnh, bóng bay cao, rơi nhanh xuống và nảy vọt về trước, cực khó cho người ở lưới.", ["doubles_strategy", "topspin"]),
("approach_shot", "Approach Shot", "Cú đánh tiến lưới (approach shot)",
 ["cú đánh lên lưới", "approach"], "strokes",
 "Cú đánh sâu, chắc, kèm theo bước tiến lên lưới ngay sau đó.", ["doubles_strategy", "tennis_tactics"]),
("passing_shot", "Passing Shot", "Cú đánh xuyên qua (passing shot)",
 ["cú đánh vượt qua", "passing"], "strokes",
 "Cú đánh nhằm vượt qua người chơi đang đứng ở lưới.", ["art_of_doubles", "tennis_tactics"]),
("cross_court", "Cross-Court", "Đánh chéo sân (cross-court)",
 ["đánh chéo góc", "chéo sân"], "strokes",
 "Đánh bóng theo đường chéo từ góc sân này sang góc sân đối diện.", ["tennis_tactics", "pattern_play"]),
("down_the_line", "Down the Line (DTL)", "Đánh dọc biên (down-the-line)",
 ["đánh thẳng biên", "đánh dọc đường biên", "DTL"], "strokes",
 "Đánh bóng song song với đường biên dọc, ít an toàn hơn cross-court nhưng bất ngờ hơn.", ["tennis_tactics", "pattern_play"]),
("inside_out", "Inside-Out Forehand", "Forehand chạy vòng đánh chéo (inside-out)",
 ["forehand chạy né", "forehand lách trái"], "strokes",
 "Chạy vòng qua backhand để đánh forehand chéo sân từ phía trái sân (với người thuận tay phải).", ["pattern_play", "tennis_tactics"]),
("inside_in", "Inside-In Forehand", "Forehand chạy vòng đánh dọc biên (inside-in)",
 ["forehand lách trong", "inside in"], "strokes",
 "Chạy vòng qua backhand để đánh forehand dọc biên cùng phía, dùng để kết thúc điểm khi có khoảng trống.", ["pattern_play", "tennis_tactics"]),
("dink", "Dink", "Cú đánh nhẹ (dink)",
 ["đánh nhẹ", "bóng dink"], "strokes",
 "Cú đánh rất nhẹ, thường là vô-lê hoặc nửa vô-lê, đưa bóng rơi ngắn và chậm để phá nhịp đối thủ.", ["art_of_doubles", "doubles_strategy"]),
("touch_shot", "Touch Shot", "Cú đánh cảm giác (touch)",
 ["cú đánh tinh tế", "bóng cảm giác"], "strokes",
 "Cú đánh đòi hỏi kiểm soát tinh tế, dùng độ mềm tay để đặt bóng ngắn hoặc thay đổi nhịp.", ["art_of_doubles", "laver"]),
("swing_volley_drive", "Drive Volley", "Vô-lê tấn công (drive volley)",
 ["volley drive", "vô lê đánh mạnh"], "strokes",
 "Vô-lê với đường vung như một cú groundstroke, đánh mạnh và có xoáy để kết thúc điểm gần lưới.", ["modern_volley", "art_modern_tennis"]),
("squash_shot", "Squash Shot", "Cú đánh kiểu squash",
 ["cú đánh cứu bóng rộng", "squash shot"], "strokes",
 "Cú đánh phòng ngự khi bị kéo ra ngoài biên, với mặt vợt mở, cắt bóng trở lại sân trong tư thế trượt dài.", ["modern_volley", "doubles_strategy"]),

# ───────────────────────────── TACTICS ─────────────────────────────
("pattern_of_play", "Pattern of Play", "Mẫu hình đường bóng (pattern of play)",
 ["chuỗi bài đánh", "mô hình chiến thuật", "pattern"], "tactics",
 "Chuỗi đường bóng lặp lại có chủ đích nhằm dẫn dắt đối thủ vào tình huống bất lợi.", ["pattern_play", "tennis_tactics"]),
("serve_plus_one", "Serve +1", "Giao bóng +1",
 ["serve plus one", "giao bóng và cú tiếp theo"], "tactics",
 "Chiến thuật lên kế hoạch sẵn cú đánh tiếp theo của mình sau khi giao bóng, nhằm chiếm thế chủ động ở bóng thứ ba.", ["pattern_play", "paradigm_shift"]),
("return_plus_one", "Return +1", "Trả giao bóng +1",
 ["return plus one", "trả bóng và cú tiếp theo"], "tactics",
 "Chiến thuật chuẩn bị sẵn cú đánh thứ ba sau khi trả giao bóng, nhằm nắm thế chủ động ngay từ đầu điểm.", ["pattern_play", "return_of_serve"]),
("percentage_tennis", "Percentage Tennis", "Quần vợt xác suất (percentage tennis)",
 ["đánh bóng an toàn", "chiến thuật xác suất cao"], "tactics",
 "Lối chơi chọn cú đánh có xác suất thành công cao nhất trong từng tình huống, hạn chế rủi ro không cần thiết.", ["how_to_play_winning", "strokes_strategies"]),
("high_percentage_shot", "High-Percentage Shot", "Cú đánh xác suất cao",
 ["cú đánh an toàn", "bóng an toàn"], "tactics",
 "Cú đánh với biên an toàn lớn: đánh chéo sân, qua lưới cao và rơi sâu trong sân.", ["strokes_strategies", "competitive_tennis"]),
("neutral_ball", "Neutral Ball", "Bóng trung tính (neutral ball)",
 ["bóng cân bằng", "bóng trung hòa"], "tactics",
 "Đường bóng không tạo lợi thế rõ rệt cho bên nào, thường đánh giữa sân với độ sâu vừa phải.", ["pattern_play", "tennis_tactics"]),
("offensive_ball", "Offensive Ball", "Bóng tấn công",
 ["bóng chủ động", "bóng áp đảo"], "tactics",
 "Đường bóng đặt đối thủ vào thế phòng ngự.", ["tennis_tactics", "competitive_tennis"]),
("defensive_ball", "Defensive Ball", "Bóng phòng ngự",
 ["bóng thủ", "bóng chống đỡ"], "tactics",
 "Đường bóng nhằm mục đích duy trì điểm và tránh sai lầm, không nhằm ghi điểm ngay.", ["tennis_tactics", "competitive_tennis"]),
("shot_angle", "Shot Angle", "Góc mở của cú đánh",
 ["góc đánh bóng", "góc mở"], "tactics",
 "Góc lệch của đường bóng so với đường thẳng vuông góc lưới, dùng để kéo giãn đối thủ.", ["tennis_tactics", "court_geometry"]),
("depth_control", "Depth (Ball Depth)", "Độ sâu của bóng",
 ["độ dài bóng", "khoảng cách rơi bóng", "độ sâu"], "tactics",
 "Khoảng cách từ lưới đến điểm bóng nảy trong sân đối phương.", ["tennis_tactics", "strokes_strategies"]),
("court_positioning", "Court Positioning", "Vị trí trên sân",
 ["thế đứng chiến thuật", "vị trí chiến thuật"], "tactics",
 "Vị trí người chơi chọn theo từng tình huống, quyết định các góc bóng mình phải phòng và có thể tấn công.", ["tennis_tactics", "spatial_dynamics"]),
("court_geometry", "Court Geometry", "Hình học sân",
 ["hình học không gian sân", "góc độ sân"], "tactics",
 "Ứng dụng kích thước và góc của sân để chọn đường bóng tối ưu về mặt không gian.", ["spatial_dynamics", "court_geometry"]),
("directionals", "Directionals (Wardlaw Directionals)", "Nguyên lý hướng bóng (directionals)",
 ["quy tắc hướng đánh", "nguyên lý Wardlaw"], "tactics",
 "Hệ quy tắc chọn hướng đánh dựa trên hướng và vị trí bóng tới, tối ưu xác suất và an toàn.", ["how_to_play_winning", "strokes_strategies"]),
("change_of_direction", "Change of Direction", "Đổi hướng bóng",
 ["đổi hướng", "chuyển hướng"], "tactics",
 "Đánh bóng sang hướng khác với đường bóng tới; rủi ro cao hơn nhưng tạo bất ngờ lớn.", ["strokes_strategies", "pattern_play"]),
("tempo_rhythm", "Tempo / Rhythm", "Nhịp điệu trận đấu",
 ["nhịp thi đấu", "nhịp độ"], "tactics",
 "Tốc độ và nhịp độ trao đổi bóng mà một bên áp đặt lên trận đấu.", ["tennis_tactics", "competitive_tennis"]),
("disguise", "Disguise / Deception", "Đánh lừa (disguise)",
 ["giấu ý đồ", "đánh lừa đối thủ"], "tactics",
 "Giữ tư thế và động tác giống nhau cho nhiều loại bóng khác nhau, khiến đối thủ không đọc được ý đồ.", ["tennis_tactics", "doubles_strategy"]),
("unforced_error", "Unforced Error", "Lỗi tự đánh hỏng (unforced error)",
 ["lỗi không bị ép", "lỗi tự mắc phải"], "tactics",
 "Sai lầm xảy ra mà không do áp lực trực tiếp từ cú đánh của đối thủ.", ["competitive_tennis", "mental_toughness"]),
("forced_error", "Forced Error", "Lỗi bị ép buộc (forced error)",
 ["lỗi do bị ép", "lỗi bị động"], "tactics",
 "Sai lầm xảy ra do áp lực từ một cú đánh tốt của đối thủ.", ["competitive_tennis", "tennis_tactics"]),
("heavy_ball", "Heavy Ball", "Bóng nặng (heavy ball)",
 ["bóng nảy vọt", "bóng xoáy nặng"], "tactics",
 "Bóng với xoáy lên cao và tốc độ lớn, nảy vọt về phía trước, cảm giác rất nặng khi đón.", ["topspin", "art_modern_tennis"]),
("moonball", "Moonball", "Bóng mặt trăng (moonball)",
 ["bóng lốp cao", "bóng vòng cung cao"], "tactics",
 "Bóng có quỹ đạo vòng cung rất cao và sâu, dùng để phòng ngự, mua thời gian hoặc phá nhịp tấn công.", ["competitive_tennis", "strokes_strategies"]),
("sitter", "Sitter", "Bóng ngon ăn (sitter)",
 ["bóng dễ", "bóng thuận lợi"], "tactics",
 "Bóng ngắn, chậm, cao rơi vào giữa sân, mời gọi một cú kết thúc.", ["tennis_tactics", "competitive_tennis"]),
("rally", "Rally", "Pha bóng qua lại (rally)",
 ["trao đổi bóng", "đánh qua lại"], "tactics",
 "Chuỗi các cú đánh qua lại giữa hai bên sau khi giao bóng thành công.", ["strokes_strategies", "competitive_tennis"]),
("winner", "Winner", "Cú ghi điểm trực tiếp (winner)",
 ["bóng thắng", "cú ăn điểm"], "tactics",
 "Cú đánh khiến đối thủ không thể chạm bóng, trực tiếp thắng điểm.", ["tennis_tactics", "competitive_tennis"]),
("big_point", "Big Point", "Điểm quan trọng (big point)",
 ["điểm then chốt", "điểm lớn"], "tactics",
 "Điểm có ảnh hưởng lớn đến cục diện trận đấu (break point, set point, match point), đòi hỏi lựa chọn chiến thuật khác biệt.", ["mental_toughness", "competitive_tennis"]),
("first_strike_tennis", "First-Strike Tennis", "Quần vợt ra đòn trước",
 ["đánh đòn quyết định đầu tiên", "first-strike"], "tactics",
 "Lối chơi chủ động tìm cơ hội dứt điểm ngay trong hai đến ba bóng đầu của mỗi điểm.", ["paradigm_shift", "tennis_2000"]),
("net_rusher", "Net Rusher / Serve-and-Volleyer", "Người lên lưới (net rusher)",
 ["người lên lưới", "đánh giao bóng lên lưới"], "player_archetypes",
 "Người chơi chủ động tiến lên lưới ngay sau phần lớn các cú đánh của mình.", ["laver", "doubles_modern"]),
("counterpuncher", "Counterpuncher", "Người đánh phản công",
 ["đánh phản công", "counter-puncher"], "player_archetypes",
 "Người chơi phòng ngự vững vàng, hấp thụ lực và tận dụng tốc độ bóng của đối thủ để phản công.", ["competitive_tennis", "strokes_of_genius"]),
("aggressive_baseliner", "Aggressive Baseliner", "Người đánh nền tấn công",
 ["baseliner tấn công", "đánh cuối sân chủ động"], "player_archetypes",
 "Người chơi tấn công từ cuối sân bằng cú đánh nền mạnh mẽ thay vì lên lưới.", ["strokes_of_genius", "competitive_tennis"]),
("all_court_player", "All-Court Player", "Người chơi toàn sân",
 ["toàn sân", "all-court"], "player_archetypes",
 "Người chơi thành thạo cả lối đánh nền tấn công lẫn lên lưới, thích ứng linh hoạt với mọi tình huống.", ["strokes_of_genius", "tennis_tactics"]),
("winner_to_error_ratio", "Winner-to-Error Ratio", "Tỷ lệ winner/lỗi",
 ["tỷ lệ ăn điểm trên lỗi", "hiệu số winner-lỗi"], "stats_analytics",
 "Chỉ số so sánh số winner với số lỗi tự đánh hỏng; thước đo mức độ hiệu quả và rủi ro của lối chơi.", ["stats_analytics", "competitive_tennis"]),

# ───────────────────────────── DOUBLES ─────────────────────────────
("poaching", "Poaching", "Cắt lưới cướp điểm (poaching)",
 ["bọc lưới", "chặn bóng cướp phần"], "doubles",
 "Người ở lưới di chuyển sang phần sân của đồng đội để chặn bóng và kết thúc điểm.", ["art_of_doubles", "doubles_strategy"]),
("i_formation", "I-Formation", "Đội hình chữ I (I-formation)",
 ["thế đứng chữ I", "I formation"], "doubles",
 "Đội hình giao bóng đôi trong đó cả hai người cùng đứng gần đường giữa trước khi giao bóng.", ["doubles_modern", "art_of_doubles"]),
("australian_formation", "Australian Formation", "Đội hình Australia",
 ["thế đứng Úc", "australian formation"], "doubles",
 "Người giao bóng và đồng đội đứng cùng một bên sân để che một đường đánh chéo.", ["doubles_modern", "art_of_doubles"]),
("one_up_one_back", "One-Up-One-Back", "Đội hình một lên một xuống",
 ["một trước một sau", "một lưới một nền"], "doubles",
 "Một người ở lưới, một người ở cuối sân — đội hình đôi truyền thống.", ["doubles_strategy", "art_of_doubles"]),
("two_back", "Two-Back", "Đội hình hai người cuối sân",
 ["cả hai đứng sau", "hai người nền sân"], "doubles",
 "Cả hai người chơi đôi cùng lùi về cuối sân, thường dùng khi bị lốp bóng hoặc phòng ngự.", ["doubles_modern", "art_of_doubles"]),
("net_partner", "Net Partner", "Đồng đội đứng lưới",
 ["đồng đội trên lưới", "partner lưới"], "doubles",
 "Người chơi đôi đứng gần lưới trong khi đồng đội giao/nhận bóng ở cuối sân.", ["art_of_doubles", "doubles_strategy"]),
("middle_theory", "Middle Theory / Middle Ball", "Nguyên lý đánh vào giữa sân",
 ["chiến thuật đánh giữa", "bóng giữa sân đôi"], "doubles",
 "Đánh bóng vào khoảng giữa hai đối thủ đôi để gây nhiễu loạn trách nhiệm phòng thủ (giảm góc).", ["art_of_doubles", "doubles_strategy"]),
("doubles_alley", "Doubles Alley", "Hành lang đôi (đường biên đôi)",
 ["hành lang biên đôi", "alley"], "doubles",
 "Dải sân rộng thêm dọc hai bên chỉ dùng trong đánh đôi; biên rộng hơn cho phép góc mở lớn hơn.", ["art_of_doubles", "doubles_strategy"]),
("poach_signal", "Signal (Poach Signal)", "Tín hiệu phối hợp (signal)",
 ["ra tín hiệu", "dấu hiệu phối hợp"], "doubles",
 "Quy ước tay sau lưng giữa hai đồng đội báo trước phương án di chuyển (ở lại, poach, đổi bên).", ["doubles_modern", "art_of_doubles"]),
("switch", "Switch", "Đổi bên (switch)",
 ["đổi vị trí", "hoán vị"], "doubles",
 "Việc hai đồng đội hoán đổi vị trí ngang qua nhau để lấp khoảng trống sau một đường bóng chéo sân.", ["doubles_modern", "art_of_doubles"]),
("fake", "Fake (Feint)", "Động tác giả (fake)",
 ["giả động tác", "feint"], "doubles",
 "Động tác giả vờ poach hoặc vờ di chuyển nhằm gây nhiễu quyết định của đối thủ, rồi trở về vị trí.", ["doubles_modern", "art_of_doubles"]),
("doubles_communication", "Doubles Communication", "Giao tiếp trong đánh đôi",
 ["phối hợp đánh đôi", "trao đổi chiến thuật đôi"], "doubles",
 "Trao đổi giữa hai đồng đội giữa các điểm và các game (tín hiệu, lời nhắc, điều chỉnh chiến thuật).", ["doubles_strategy", "art_of_doubles"]),

# ───────────────────────────── FOOTWORK & MOVEMENT ─────────────────────────────
("split_step", "Split-Step", "Bước nhún tách chân chuẩn bị",
 ["bước nhảy tách", "bước chuẩn bị nhảy"], "footwork_movement",
 "Động tác nhún nhẹ hai chân ngay trước khi đối thủ tiếp xúc bóng.", ["bollettieri", "sports_science"]),
("ready_position", "Ready Position", "Tư thế sẵn sàng",
 ["thế chuẩn bị", "tư thế chờ"], "footwork_movement",
 "Tư thế trọng tâm thấp, hai chân rộng bằng vai, vợt nâng trước ngực, sẵn sàng bung người về mọi hướng.", ["laver", "strokes_strategies"]),
("adjustment_steps", "Adjustment Steps", "Bước điều chỉnh",
 ["bước căn chỉnh vị trí", "bước nhỏ căn"], "footwork_movement",
 "Các bước nhỏ cuối cùng để căn đúng khoảng cách và thăng bằng trước khi tiếp xúc bóng.", ["bollettieri", "strokes_strategies"]),
("recovery_step", "Recovery (Recovery Step)", "Bước hồi vị",
 ["bước trở lại vị trí", "hồi phục vị trí"], "footwork_movement",
 "Di chuyển trở lại vị trí trung tâm/chiến thuật sau khi thực hiện cú đánh.", ["tennis_anatomy", "competitive_tennis"]),
("crossover_step", "Crossover Step", "Bước chân bắt chéo",
 ["bước chéo chân", "bắt chéo"], "footwork_movement",
 "Kỹ thuật di chuyển nhanh sang ngang bằng cách bắt chéo hai chân, dùng cho quãng đường dài.", ["tennis_anatomy", "sports_science"]),
("shuffle_step", "Shuffle Step / Side Step", "Bước trượt ngang",
 ["bước lê chân", "bước ngang nhỏ", "side-shuffle"], "footwork_movement",
 "Bước di chuyển ngang nhỏ, giữ trọng tâm thấp, dùng cho quãng đường ngắn gần lưới.", ["tennis_anatomy", "modern_volley"]),
("gravity_step", "Gravity Step", "Bước tận dụng trọng lực",
 ["bước rơi người", "gravity step"], "footwork_movement",
 "Bước hồi vị đầu tiên tận dụng đà và trọng lực cơ thể, giúp bật lại nhanh hơn mà ít tốn sức.", ["tennis_anatomy", "paradigm_shift"]),
("open_stance", "Open Stance", "Tư thế đứng mở",
 ["thế đứng mở người", "đứng ngang mở"], "footwork_movement",
 "Hai vai và hông song song với lưới khi đánh bóng, phổ biến ở forehand hiện đại.", ["bollettieri", "art_modern_tennis"]),
("semi_open_stance", "Semi-Open Stance", "Tư thế đứng bán mở",
 ["đứng nửa mở", "semi-open"], "footwork_movement",
 "Trung gian giữa đứng mở và đứng ngang (closed stance).", ["bollettieri", "art_modern_tennis"]),
("closed_stance", "Closed Stance", "Tư thế đứng ngang (đóng)",
 ["đứng đóng", "closed stance"], "footwork_movement",
 "Chân trước bước chéo qua, vai vuông góc với lưới; thường dùng cho slice hoặc cú đánh kiểm soát.", ["bollettieri", "strokes_strategies"]),
("neutral_stance", "Neutral Stance", "Tư thế đứng trung tính",
 ["đứng thẳng hướng", "neutral stance"], "footwork_movement",
 "Hai chân đặt ngang hàng hướng về lưới, phù hợp với cú đánh cần bước tới và chuyển trọng tâm về trước.", ["bollettieri", "strokes_strategies"]),
("footwork", "Footwork", "Bước chân (footwork)",
 ["kỹ thuật bước chân", "di chuyển chân"], "footwork_movement",
 "Toàn bộ kỹ thuật di chuyển trên sân: bước nhỏ, bước dài, bắt chéo, hồi vị — nền tảng để đánh bóng đúng vị trí.", ["bollettieri", "tennis_anatomy"]),
("movement_patterns", "Movement Patterns", "Mẫu di chuyển",
 ["đường di chuyển", "pattern di chuyển"], "footwork_movement",
 "Các chuỗi bước được huấn luyện thành tự động hóa cho từng tình huống sân (ngang, chéo, tới, lui).", ["tennis_anatomy", "spatial_dynamics"]),
("carioca", "Carioca Step", "Bước carioca",
 ["bước chéo liên tục", "chạy carioca"], "footwork_movement",
 "Bài tập di chuyển ngang bằng cách bắt chéo trước–sau liên tục, dùng để luyện phối hợp và tốc độ chân.", ["complete_conditioning", "sports_science"]),

# ───────────────────────────── MENTAL & PSYCHOLOGY ─────────────────────────────
("choking", "Choking (Under Pressure)", "Hiện tượng 'nghẹt thở' tâm lý (choking)",
 ["tâm lý hoảng loạn", "vỡ trận tâm lý", "choking"], "mental_psychology",
 "Sự sụt giảm hiệu suất đột ngột do áp lực tâm lý quá mức ở thời điểm quyết định.", ["mental_toughness", "tennis_mind"]),
("visualization", "Visualization / Mental Imagery", "Hình dung tinh thần (visualization)",
 ["tưởng tượng trước trận", "hình dung trong đầu", "mental imagery"], "mental_psychology",
 "Kỹ thuật tâm lý tưởng tượng trước các tình huống/kết quả để chuẩn bị tinh thần.", ["visual_tennis", "tennis_mind"]),
("anticipation", "Anticipation", "Khả năng đoán trước (anticipation)",
 ["dự đoán tình huống", "phán đoán bóng"], "mental_psychology",
 "Kỹ năng đọc tín hiệu cơ thể/vợt đối thủ để dự đoán hướng bóng trước khi tiếp xúc.", ["tennis_anatomy", "competitive_tennis"]),
("focus_concentration", "Focus / Concentration", "Sự tập trung",
 ["khả năng chú ý", "tập trung tinh thần"], "mental_psychology",
 "Trạng thái duy trì sự chú ý vào nhiệm vụ hiện tại (điểm bóng đang diễn ra).", ["focused_tennis", "inner_game"]),
("flow_state", "Flow State / The Zone", "Trạng thái dòng chảy (flow state)",
 ["vùng thi đấu đỉnh cao", "trạng thái xuất thần", "the zone"], "mental_psychology",
 "Trạng thái tâm lý tối ưu, thi đấu tự nhiên không suy nghĩ, tập trung tuyệt đối.", ["inner_game", "mental_toughness"]),
("arousal", "Arousal / Activation", "Mức hưng phấn (arousal)",
 ["mức kích hoạt", "hưng phấn tâm lý"], "mental_psychology",
 "Mức độ tỉnh táo và kích hoạt sinh lý; quá thấp (uể oải) hoặc quá cao (căng cứng) đều hại hiệu suất.", ["mental_toughness", "tennis_mind"]),
("self_talk", "Self-Talk", "Tự nói với mình (self-talk)",
 ["độc thoại nội tâm", "tự nhắc bản thân"], "mental_psychology",
 "Dùng lời nói nội tâm hướng dẫn hoặc động viên bản thân; có thể là chỉ dẫn kỹ thuật hoặc khích lệ.", ["mental_toughness", "tennis_mind"]),
("pre_shot_routine", "Pre-Shot Routine", "Quy trình trước cú đánh",
 ["thói quen trước đánh", "routine trước cú"], "mental_psychology",
 "Chuỗi hành động cố định trước mỗi cú đánh giúp ổn định sự tập trung và kích hoạt động tác tự động.", ["mental_toughness", "focused_tennis"]),
("between_point_routine", "Between-Point Routine", "Quy trình giữa các điểm",
 ["thói quen giữa điểm", "routine giữa điểm"], "mental_psychology",
 "Nghi thức cố định giữa các điểm (thở, lau mồ hôi, chỉnh dây) để xử lý cảm xúc và tái tập trung.", ["mental_toughness", "tennis_confidential"]),
("process_goals", "Process Goals", "Mục tiêu quá trình",
 ["mục tiêu quá trình", "goal quá trình"], "mental_psychology",
 "Mục tiêu tập trung vào điều mình kiểm soát được (nhịp chân, bước chuẩn bị) thay vì kết quả cuối cùng.", ["mental_toughness", "focused_tennis"]),
("outcome_goals", "Outcome Goals", "Mục tiêu kết quả",
 ["mục tiêu kết quả", "goal kết quả"], "mental_psychology",
 "Mục tiêu hướng đến kết quả cuối (thắng trận, thứ hạng); nên dùng cho kế hoạch dài hạn, không cho từng điểm.", ["mental_toughness", "focused_tennis"]),
("box_breathing", "Box Breathing", "Hít thở hình vuông (box breathing)",
 ["thở 4-4-4-4", "hít thở kiểm soát"], "mental_psychology",
 "Kỹ thuật thở theo nhịp đều bốn pha, dùng để hạ mức hưng phấn và tái lập sự bình tĩnh giữa các điểm.", ["mental_toughness", "tennis_mind"]),
("momentum", "Momentum", "Đà tâm lý trận đấu (momentum)",
 ["thế thắng", "đà trận đấu"], "mental_psychology",
 "Xu hướng dịch chuyển lợi thế tâm lý và điểm số về một phía trong một giai đoạn của trận đấu.", ["competitive_tennis", "mental_toughness"]),
("clutch", "Clutch", "Bản lĩnh ở điểm quyết định (clutch)",
 ["tâm lý thép", "chơi tốt lúc then chốt"], "mental_psychology",
 "Khả năng nâng hiệu suất lên cao nhất ở những điểm quan trọng thay vì bị áp lực bóp nghẹt.", ["mental_toughness", "competitive_tennis"]),
("confidence", "Confidence / Self-Belief", "Sự tự tin",
 ["tự tin", "niềm tin bản thân"], "mental_psychology",
 "Mức độ tin tưởng vào khả năng của mình; được xây dựng từ thành tích luyện tập và trải nghiệm thi đấu.", ["mental_toughness", "focused_tennis"]),
("tanking", "Tanking", "Buông trận (tanking)",
 ["bỏ mặc trận đấu", "đánh cho có"], "mental_psychology",
 "Việc người chơi chủ động hoặc vô thức hạ thấp nỗ lực như một cách trốn tránh áp lực của việc thua.", ["tennis_confidential", "tennis_mind"]),
("refocusing", "Refocusing Cue", "Nhắc tái tập trung (refocus)",
 ["tín hiệu tập trung lại", "câu nhắc tập trung"], "mental_psychology",
 "Từ khóa hoặc cử chỉ ngắn dùng để kéo sự chú ý trở lại sau một điểm hỏng hoặc một sai sót.", ["mental_toughness", "focused_tennis"]),

# ───────────────────────────── TRAINING & CONDITIONING ─────────────────────────────
("periodization", "Periodization", "Chu kỳ hóa tập luyện (periodization)",
 ["phân kỳ huấn luyện", "chu kỳ tập luyện"], "training_conditioning",
 "Chia chương trình tập luyện thành các giai đoạn có mục tiêu khác nhau trong năm.", ["complete_conditioning", "sports_science"]),
("motor_learning", "Motor Learning", "Học vận động (motor learning)",
 ["học kỹ năng vận động", "huấn luyện thần kinh cơ"], "training_conditioning",
 "Quá trình hình thành và củng cố kỹ năng vận động qua luyện tập lặp lại.", ["motor_learning", "science_of_coaching"]),
("muscle_memory", "Muscle Memory", "Trí nhớ cơ (muscle memory)",
 ["ký ức cơ bắp", "trí nhớ vận động"], "training_conditioning",
 "Khả năng thực hiện động tác tự động hóa nhờ luyện tập lặp lại nhiều lần.", ["motor_learning", "tennis_anatomy"]),
("reaction_time", "Reaction Time", "Thời gian phản xạ",
 ["tốc độ phản ứng", "thời gian phản ứng"], "training_conditioning",
 "Khoảng thời gian từ khi nhận kích thích (bóng rời vợt đối thủ) đến khi bắt đầu phản ứng.", ["sports_science", "tennis_anatomy"]),
("shadow_swing", "Shadow Swing", "Vung vợt không bóng (shadow swing)",
 ["đánh khống", "vung tay không"], "training_conditioning",
 "Luyện tập kỹ thuật vung vợt mà không có bóng thật, tập trung vào cơ chế chuyển động.", ["motor_learning", "coaching_tennis"]),
("conditioning", "Conditioning", "Rèn luyện thể lực (conditioning)",
 ["thể lực nền", "huấn luyện thể chất"], "training_conditioning",
 "Chương trình rèn luyện sức bền, sức mạnh và tốc độ chuyên biệt cho quần vợt.", ["complete_conditioning", "total_health"]),
("plyometrics", "Plyometrics", "Bài tập bật nhảy (plyometrics)",
 ["bài tập bật nảy", "plyometric"], "training_conditioning",
 "Bài tập sử dụng chu kỳ căng–co rút nhanh (bật nhảy, nhảy dây, nhảy biên) để tăng sức mạnh bùng nổ.", ["complete_conditioning", "sports_science"]),
("agility_ladder", "Agility Ladder", "Thang luyện nhanh nhẹn",
 ["thang agility", "luyện bước nhanh"], "training_conditioning",
 "Dụng cụ dạng thang đặt trên sân dùng để luyện tần số bước và phối hợp chân.", ["complete_conditioning", "coaching_youth"]),
("dynamic_warmup", "Dynamic Warm-up", "Khởi động động (dynamic warm-up)",
 ["khởi động năng động", "warm-up động"], "training_conditioning",
 "Chuỗi động tác vận động liên tục (xoay vai, đá chân, xoay hông) làm nóng cơ thể trước khi thi đấu.", ["complete_conditioning", "total_health"]),
("static_stretching", "Static Stretching", "Giãn cơ tĩnh (static stretching)",
 ["kéo giãn tĩnh", "giãn cơ giữ yên"], "training_conditioning",
 "Giữ một tư thế giãn trong nhiều giây; nên thực hiện sau tập/thi đấu hơn là trước khi vào trận.", ["complete_conditioning", "total_health"]),
("mobility", "Mobility", "Khả năng vận động khớp (mobility)",
 ["linh hoạt khớp", "biên độ vận động"], "training_conditioning",
 "Biên độ chủ động quanh một khớp; ảnh hưởng trực tiếp đến tư thế đánh và nguy cơ chấn thương.", ["complete_conditioning", "tennis_medicine"]),
("core_stability", "Core Stability", "Ổn định vùng lõi",
 ["ổn định thân người", "sức mạnh core"], "training_conditioning",
 "Khả năng giữ vững thân người dưới tải trọng xoay và lệch, nền tảng để truyền lực hiệu quả.", ["tennis_anatomy", "complete_conditioning"]),
("overtraining", "Overtraining", "Tập luyện quá tải",
 ["luyện tập quá độ", "quá tải tập luyện"], "training_conditioning",
 "Trạng thái suy giảm hiệu suất kéo dài do khối lượng/khoa tập vượt quá khả năng hồi phục.", ["complete_conditioning", "total_health"]),
("burnout", "Burnout", "Kiệt sức tâm lý (burnout)",
 ["chán thi đấu", "kiệt sức thi đấu"], "training_conditioning",
 "Trạng thái mất động lực, kiệt sức cảm xúc do cường độ thi đấu và huấn luyện kéo dài.", ["tennis_mind", "competitive_tennis"]),
("tapering", "Tapering", "Giảm khối lượng trước giải (tapering)",
 ["giảm tải trước giải", "taper"], "training_conditioning",
 "Chủ động giảm khối lượng tập luyện trước giải đấu để cơ thể đạt đỉnh phong độ.", ["complete_conditioning", "sports_science"]),
("video_analysis", "Video Analysis", "Phân tích video",
 ["quay phim phân tích", "phân tích kỹ thuật qua video"], "training_conditioning",
 "Ghi hình và phân tích kỹ thuật của bản thân hoặc đối thủ để phát hiện lỗi và điều chỉnh.", ["high_tech_tennis", "science_of_coaching"]),
("ball_machine", "Ball Machine", "Máy bắn bóng",
 ["máy giao bóng", "máy ném bóng"], "training_conditioning",
 "Thiết bị bắn bóng tự động theo cài đặt tốc độ, xoáy và điểm rơi, dùng để luyện tập lặp lại.", ["high_tech_tennis", "tennis_drill"]),
("basket_feeding", "Basket Feeding", "Tung bóng rổ (basket feeding)",
 ["cho bóng từ rổ", "tung bóng huấn luyện"], "training_conditioning",
 "Huấn luyện viên tung bóng liên tục từ rổ cho học viên đánh, dùng để luyện khối lượng lớn cú đánh.", ["coaching_tennis", "teaching_tennis"]),
("drill", "Drill", "Bài tập (drill)",
 ["bài tập kỹ thuật", "bài luyện"], "training_conditioning",
 "Bài tập có cấu trúc nhắm vào một kỹ năng hoặc tình huống cụ thể, thường lặp lại nhiều lần.", ["tennis_drill", "coaching_tennis"]),

# ───────────────────────────── EQUIPMENT & SCORING ─────────────────────────────
("grip_continental", "Continental Grip", "Cách cầm vợt Continental",
 ["cầm vợt kiểu lục địa", "grip continental"], "equipment_scoring",
 "Kiểu cầm vợt trung tính, dùng cho giao bóng, vô-lê và slice.", ["laver", "strokes_strategies"]),
("grip_eastern", "Eastern Grip", "Cách cầm vợt Eastern",
 ["cầm vợt kiểu Đông", "grip eastern"], "equipment_scoring",
 "Kiểu cầm vợt bán-Tây, phù hợp bóng độ cao trung bình.", ["laver", "strokes_strategies"]),
("grip_western", "Western / Semi-Western Grip", "Cách cầm vợt Western / Bán-Western",
 ["cầm vợt kiểu Tây", "grip western", "semi-western"], "equipment_scoring",
 "Kiểu cầm vợt phổ biến trong forehand hiện đại, tạo topspin cao.", ["art_modern_tennis", "strokes_strategies"]),
("bevels", "Bevels", "Các mặt cán vợt (bevels)",
 ["mặt vát cán vợt", "cạnh cán vợt"], "equipment_scoring",
 "Tám mặt phẳng của cán vợt; mỗi kiểu cầm vợt được định nghĩa bằng mặt bevel mà gốc ngón trỏ đặt vào.", ["strokes_strategies", "high_tech_tennis"]),
("butt_cap", "Butt Cap", "Đuôi cán vợt (butt cap)",
 ["chóp cán", "đáy cán vợt"], "equipment_scoring",
 "Phần chóp ở cuối cán vợt; là điểm neo cho bàn tay dưới và mốc tham chiếu để xác định kiểu cầm.", ["high_tech_tennis", "strokes_strategies"]),
("sweet_spot", "Sweet Spot", "Điểm ngọt (sweet spot)",
 ["điểm ngọt trên mặt vợt", "vùng ngọt"], "equipment_scoring",
 "Vùng trên mặt dây cho cảm giác và tốc độ bóng tốt nhất, gần như không rung khi tiếp xúc.", ["high_tech_tennis", "tennis_2000"]),
("string_tension", "String Tension", "Độ căng dây vợt",
 ["lực căng dây", "tension dây"], "equipment_scoring",
 "Độ căng của dây lưới, thường đo bằng pound; căng cao hơn cho kiểm soát, căng thấp hơn cho lực và độ nảy.", ["high_tech_tennis", "tennis_2000"]),
("head_size", "Head Size", "Diện tích mặt vợt",
 ["kích thước mặt vợt", "mặt vợt lớn nhỏ"], "equipment_scoring",
 "Diện tích mặt lưới của vợt (inch vuông); mặt lớn cho vùng ngọt rộng và khoan dung lỗi cao hơn.", ["high_tech_tennis", "tennis_2000"]),
("balance_point", "Balance Point", "Điểm cân bằng vợt",
 ["độ cân bằng vợt", "balance"], "equipment_scoring",
 "Vị trí trọng tâm dọc theo chiều dài vợt; quyết định cảm giác nặng đầu hay nhẹ đầu khi vung.", ["high_tech_tennis", "tennis_2000"]),
("swingweight", "Swingweight", "Trọng lượng khi vung (swingweight)",
 ["quán tính vợt", "độ nặng khi vung"], "equipment_scoring",
 "Đại lượng đo quán tính quay của vợt; quyết định độ nặng tay cảm nhận khi vung và khả năng ổn định khi đỡ bóng mạnh.", ["high_tech_tennis", "tennis_2000"]),
("racquet_face", "Racquet Face", "Mặt vợt",
 ["mặt dây", "mặt phẳng vợt"], "equipment_scoring",
 "Mặt phẳng của khung và dây vợt tại điểm tiếp xúc; góc mở/đóng của nó quyết định hướng và độ xoáy của bóng.", ["strokes_strategies", "high_tech_tennis"]),
("break_point", "Break Point", "Điểm bẻ giao bóng (break point)",
 ["điểm phá giao", "điểm bẻ giao"], "equipment_scoring",
 "Điểm mà người nhận giao bóng có cơ hội thắng ván đấu của đối thủ đang giao bóng.", ["tennis_tactics", "competitive_tennis"]),
("ace", "Ace", "Giao bóng ăn điểm trực tiếp (ace)",
 ["giao bóng không chạm", "ace"], "equipment_scoring",
 "Giao bóng thành công mà người nhận không chạm được vào bóng.", ["laver", "competitive_tennis"]),
("double_fault", "Double Fault", "Lỗi giao bóng kép (double fault)",
 ["giao bóng hỏng hai lần", "lỗi hai giao bóng"], "equipment_scoring",
 "Hai lần giao bóng liên tiếp đều hỏng, khiến người giao bóng mất điểm.", ["competitive_tennis", "rules_officiating"]),
("foot_fault", "Foot Fault", "Lỗi chân (foot fault)",
 ["lỗi giẫm vạch", "phạm lỗi chân"], "rules_officiating",
 "Lỗi xảy ra khi chân người giao bóng chạm vạch cuối sân hoặc vào trong sân trước khi vợt tiếp xúc bóng.", ["rules_officiating", "laver"]),
("let", "Let", "Bóng chạm lưới (let)",
 ["bóng chạm dây lưới", "let bóng"], "equipment_scoring",
 "Tình huống bóng giao chạm dây lưới rồi rơi vào ô giao bóng hợp lệ; cú giao bóng được đánh lại, không tính lỗi.", ["rules_officiating", "tennis_tactics"]),
("tiebreak", "Tiebreak", "Loạt đánh quyết định (tiebreak)",
 ["tie-break", "đánh bảy điểm"], "equipment_scoring",
 "Thể thức tính điểm thay cho ván đấu khi tỷ số game đạt 6–6, thường đấu đến 7 điểm và phải hơn 2 điểm.", ["rules_officiating", "competitive_tennis"]),
("deuce", "Deuce", "Điểm 40–40 (deuce)",
 ["hòa 40-40", "deuce"], "equipment_scoring",
 "Tỷ số 40–40 trong một game, khi đó một bên phải thắng liên tiếp hai điểm để thắng game.", ["rules_officiating", "tennis_tactics"]),
("advantage", "Advantage", "Điểm lợi thế (advantage)",
 ["lợi thế", "điểm ưu thế"], "equipment_scoring",
 "Điểm ngay sau deuce, khi một bên đã thắng một điểm; thắng điểm tiếp theo sẽ kết thúc game.", ["rules_officiating", "tennis_tactics"]),
("no_ad_scoring", "No-Ad Scoring", "Tính điểm không lợi thế (no-ad)",
 ["không deuce", "no-ad"], "rules_officiating",
 "Thể thức tại deuce chỉ đánh một điểm quyết định duy nhất, bên nhận chọn ô giao bóng; dùng ở nhiều giải đôi và đồng đội.", ["rules_officiating", "doubles_modern"]),
("deuce_court", "Deuce Court", "Ô sân Deuce (bên phải)",
 ["sân deuce", "ô phải"], "equipment_scoring",
 "Nửa sân bên phải của người chơi; điểm khởi đầu và các điểm chẵn được giao/nhận từ ô này.", ["doubles_strategy", "tennis_tactics"]),
("ad_court", "Ad Court", "Ô sân Ad (bên trái)",
 ["sân lợi thế", "ô trái"], "equipment_scoring",
 "Nửa sân bên trái của người chơi; điểm lợi thế và các điểm lẻ được giao/nhận từ ô này.", ["doubles_strategy", "tennis_tactics"]),
("match_point", "Match Point", "Điểm trận đấu (match point)",
 ["điểm kết thúc trận", "match point"], "equipment_scoring",
 "Điểm mà nếu người dẫn trước thắng sẽ kết thúc trận đấu.", ["competitive_tennis", "mental_toughness"]),
("set_point", "Set Point", "Điểm ván đấu (set point)",
 ["điểm kết thúc ván", "set point"], "equipment_scoring",
 "Điểm mà nếu người dẫn trước thắng sẽ kết thúc ván đấu.", ["competitive_tennis", "mental_toughness"]),
("game_point", "Game Point", "Điểm game (game point)",
 ["điểm kết thúc game", "game point"], "equipment_scoring",
 "Điểm mà nếu người dẫn trước thắng sẽ kết thúc game.", ["competitive_tennis", "rules_officiating"]),
("golden_point", "Golden Point", "Điểm vàng (golden point)",
 ["điểm quyết định", "golden point"], "rules_officiating",
 "Điểm duy nhất quyết định game khi tỷ số 40–40, dùng trong thể thức no-ad.", ["rules_officiating", "doubles_modern"]),

# ───────────────────────────── INJURIES & MEDICINE ─────────────────────────────
("tennis_elbow", "Tennis Elbow (Lateral Epicondylitis)", "Viêm khuỷu ngoài (tennis elbow)",
 ["đau khuỷu tay", "viêm lồi cầu ngoài"], "injuries_medical",
 "Viêm gân ở mặt ngoài khuỷu tay, do lặp lại động tác gập duỗi cổ tay và lực tác động ngược từ bóng.", ["tennis_medicine", "tennis_anatomy"]),
("golfers_elbow", "Golfer's Elbow (Medial Epicondylitis)", "Viêm khuỷu trong (golfer's elbow)",
 ["đau mặt trong khuỷu", "viêm lồi cầu trong"], "injuries_medical",
 "Viêm gân ở mặt trong khuỷu tay, thường gặp khi đánh nhiều cú topspin hoặc cú gập cổ tay.", ["tennis_medicine", "tennis_anatomy"]),
("rotator_cuff", "Rotator Cuff", "Chóp xoay vai (rotator cuff)",
 ["nhóm cơ chóp xoay", "cơ quay vai"], "injuries_medical",
 "Nhóm bốn cơ bao quanh khớp vai giữ ổn định và điều khiển xoay; chịu tải lớn trong giao bóng.", ["tennis_medicine", "tennis_anatomy"]),
("shoulder_impingement", "Shoulder Impingement", "Hội chứng chèn ép vai",
 ["chèn ép khớp vai", "kẹp vai"], "injuries_medical",
 "Tình trạng gân chóp xoay bị chèn ép dưới xương cùng vai, thường do xoay trong vai lặp lại khi giao bóng.", ["tennis_medicine", "muscle_slings"]),
("jumpers_knee", "Jumper's Knee (Patellar Tendinopathy)", "Viêm gân bánh chè (jumper's knee)",
 ["đau gân bánh chè", "viêm gân đầu gối"], "injuries_medical",
 "Viêm gân nối xương bánh chè và xương chày, do khối lượng bật nhảy và đổi hướng lớn.", ["tennis_medicine", "complete_conditioning"]),
("low_back_pain", "Low Back Pain", "Đau lưng dưới",
 ["đau thắt lưng", "đau lưng"], "injuries_medical",
 "Chấn thương phổ biến do lặp lại xoay thân dưới tải trọng lớn, điển hình ở cú giao bóng và forehand.", ["tennis_medicine", "tennis_anatomy"]),
("osgood_schlatter", "Osgood-Schlatter Disease", "Bệnh Osgood-Schlatter",
 ["viêm xương bánh chè tuổi dậy thì", "đau lồi cằm chày"], "injuries_medical",
 "Viêm nơi gân bánh chè bám vào xương chày ở người trẻ tuổi đang lớn, thường do bật nhảy nhiều.", ["coaching_youth", "tennis_medicine"]),
("warmup_injury_prevention", "Injury Prevention", "Phòng ngừa chấn thương",
 ["phòng chấn thương", "ngừa chấn thương"], "injuries_medical",
 "Tập luyện cân đối, khởi động đúng, tăng tải từ từ và hồi phục đủ để giảm nguy cơ chấn thương.", ["tennis_medicine", "complete_conditioning"]),

# ───────────────────────────── RULES & OFFICIATING ─────────────────────────────
("hawk_eye", "Hawk-Eye / Electronic Line Calling", "Hawk-Eye (Hệ thống gọi vạch điện tử)",
 ["mắt diều hâu", "công nghệ gọi vạch"], "rules_officiating",
 "Hệ thống camera dựng lại điểm rơi của bóng, dùng để xác định bóng trong hay ngoài biên.", ["high_tech_tennis", "rules_officiating"]),
("line_call_challenge", "Challenge", "Yêu cầu kiểm tra vạch (challenge)",
 ["khiếu nại bóng", "kiểm tra lại vạch"], "rules_officiating",
 "Quyền của người chơi yêu cầu hệ thống điện tử xác minh một điểm rơi bóng bị tranh cãi.", ["rules_officiating", "competitive_tennis"]),
("code_violation", "Code Violation", "Lỗi vi phạm quy tắc ứng xử",
 ["lỗi ứng xử", "cảnh cáo hành vi"], "rules_officiating",
 "Hình phạt trọng tài áp cho hành vi không đúng mực (chửi thề, đập vợt, trì hoãn); có thể dẫn tới mất điểm, mất game hoặc mất trận.", ["rules_officiating", "tennis_confidential"]),
("on_court_coaching", "On-Court Coaching", "Huấn luyện viên chỉ đạo trong trận",
 ["chỉ đạo từ khán đài", "coaching trong trận"], "rules_officiating",
 "Quy định về việc huấn luyện viên được phép trao đổi với người chơi trong trận, tùy thể thức giải đấu.", ["rules_officiating", "coaching_tennis"]),
("shot_clock", "Shot Clock", "Đồng hồ giao bóng (shot clock)",
 ["giờ giao bóng", "đồng hồ đếm giao bóng"], "rules_officiating",
 "Đồng hồ đếm ngược giới hạn thời gian giữa các điểm (thường 25 giây) mà người giao bóng phải bắt đầu giao.", ["rules_officiating", "competitive_tennis"]),

# ───────────────────────────── SURFACES & CONDITIONS ─────────────────────────────
("clay_court", "Clay Court", "Sân đất nện",
 ["sân đất", "đất nện"], "surfaces_conditions",
 "Mặt sân bằng đất nghiền, bóng nảy chậm và cao hơn, tạo điều kiện cho lối đánh bền bỉ và trượt chân.", ["strokes_strategies", "competitive_tennis"]),
("hard_court", "Hard Court", "Sân cứng",
 ["sân cứng bê tông", "hard court"], "surfaces_conditions",
 "Sân mặt cứng (bê tông hoặc acrylic), bóng nảy ổn định và nhanh, là loại sân phổ biến nhất hiện nay.", ["strokes_strategies", "competitive_tennis"]),
("grass_court", "Grass Court", "Sân cỏ",
 ["sân cỏ tự nhiên", "grass court"], "surfaces_conditions",
 "Sân cỏ, bóng đi nhanh và nảy thấp, thưởng cho lối đánh giao bóng lên lưới và cắt bóng.", ["laver", "strokes_strategies"]),
("indoor_court", "Indoor Court", "Sân trong nhà",
 ["sân mái che", "indoor court"], "surfaces_conditions",
 "Sân thi đấu trong nhà, không chịu ảnh hưởng của gió và điều kiện thời tiết, thường có bóng đi rất nhanh.", ["competitive_tennis", "tennis_2000"]),
("court_surface", "Court Surface", "Mặt sân",
 ["loại mặt sân", "chất liệu sân"], "surfaces_conditions",
 "Vật liệu bề mặt sân quyết định độ nảy, tốc độ bóng và kiểu chơi được lợi thế.", ["strokes_strategies", "competitive_tennis"]),
("heat_humidity", "Heat & Humidity", "Nóng ẩm",
 ["điều kiện nóng ẩm", "nhiệt độ và độ ẩm"], "surfaces_conditions",
 "Điều kiện khắc nghiệt gây mất nước, chuột rút và suy giảm tập trung; đòi hỏi chiến thuật và bù nước đúng.", ["complete_conditioning", "total_health"]),
("wind_conditions", "Wind Conditions", "Điều kiện gió",
 ["gió sân", "chơi trong gió"], "surfaces_conditions",
 "Gió ảnh hưởng đến quỹ đạo tung bóng giao và đường bóng; cần điều chỉnh kỹ thuật và mục tiêu chiến thuật.", ["competitive_tennis", "spatial_dynamics"]),
("altitude", "Altitude", "Độ cao so với mực nước biển",
 ["chơi ở độ cao", "độ cao sân"], "surfaces_conditions",
 "Ở độ cao lớn, không khí loãng làm bóng bay nhanh và xoáy ăn ít hơn, đòi hỏi điều chỉnh biên an toàn.", ["competitive_tennis", "tennis_science"]),

# ───────────────────────────── STATS & ANALYTICS ─────────────────────────────
("first_serve_percentage", "First Serve Percentage", "Tỷ lệ giao bóng một vào sân",
 ["% giao bóng 1", "tỷ lệ giao bóng một"], "stats_analytics",
 "Phần trăm giao bóng một thành công trên tổng số giao bóng; chỉ số then chốt của hiệu quả giao bóng.", ["stats_analytics", "competitive_tennis"]),
("unreturned_serve_pct", "Unreturned Serve %", "Tỷ lệ giao bóng không bị trả",
 ["% giao bóng thắng trực tiếp", "tỷ lệ giao không đỡ được"], "stats_analytics",
 "Phần trăm giao bóng mà người nhận không đưa được bóng vào sân (ace hoặc trả bóng hỏng).", ["stats_analytics", "competitive_tennis"]),
("net_points_won", "Net Points Won", "Tỷ lệ thắng điểm ở lưới",
 ["% điểm lưới thắng", "hiệu quả lên lưới"], "stats_analytics",
 "Phần trăm điểm thắng được khi người chơi lên lưới; thước đo hiệu quả của lối chơi tấn công lưới.", ["stats_analytics", "doubles_modern"]),
("break_points_converted", "Break Points Converted", "Tỷ lệ tận dụng điểm bẻ giao",
 ["% phá giao thành công", "hiệu quả break point"], "stats_analytics",
 "Phần trăm break point được chuyển thành game thắng; chỉ số quyết định kết quả các ván cân bằng.", ["stats_analytics", "competitive_tennis"]),
("shot_quality", "Shot Quality (SQ)", "Chất lượng cú đánh (SQ)",
 ["chỉ số chất lượng cú", "SQ"], "stats_analytics",
 "Chỉ số đo tổng hợp tốc độ, xoáy và độ sâu của một cú đánh, so với mặt bằng chung của giải đấu.", ["stats_analytics", "high_tech_tennis"]),
("data_analysis", "Data & Match Analytics", "Phân tích dữ liệu trận đấu",
 ["thống kê trận", "phân tích số liệu"], "stats_analytics",
 "Dùng số liệu (tỷ lệ giao bóng, điểm lưới, vùng bóng) để nhận diện mẫu hình và điều chỉnh chiến thuật.", ["stats_analytics", "science_of_coaching"]),
]

# ── source book registry (key -> (label, href)) ──
B = {
 "biomechanics": ("The Biomechanics of Tennis", "the_biomechanics_of_tennis_vi.html"),
 "tennis_anatomy": ("Tennis Anatomy (Roetert & Kovacs)", "tennis_anatomy_roetert_kovacs_vi.html"),
 "wave_transmission": ("Wave Transmission in Tennis", "wave_transmission_tennis_vi.html"),
 "muscle_slings": ("Muscle Slings in Tennis", "muscle_slings_in_tennis_vi.html"),
 "tennis_science": ("Tennis Science Behind Sports", "tennis_science_behind_sports_vi.html"),
 "sports_science": ("The Science Behind Sports", "tennis_science_behind_sports_vi.html"),
 "art_modern_tennis": ("The Art of Modern Tennis", "the_art_of_modern_tennis_vi.html"),
 "maximum_tennis": ("Maximum Tennis", "maximum_tennis_vi.html"),
 "paradigm_shift": ("Paradigm Shift for Future Tennis", "paradigm_shift_for_future_tennis_vi.html"),
 "high_tech_tennis": ("High-Tech Tennis", "high_tech_tennis_vi.html"),
 "topspin": ("Topspin to Better Tennis", "topspin_to_better_tennis_vi.html"),
 "bollettieri": ("Bollettieri's Tennis Handbook", "bollettieri_tennis_handbook_vi.html"),
 "laver": ("228 Tennis Tips (Rod Laver)", "228_tennis_tips_vi.html"),
 "strokes_strategies": ("Strokes and Strategies", "strokes_and_strategies_vi.html"),
 "strokes_of_genius": ("Strokes of Genius", "strokes_of_genius_federer_nadal_vi.html"),
 "tennis_2000": ("Tennis 2000", "tennis_2000_vi.html"),
 "tennis_tactics": ("Tennis Tactics", "tennis_tactics_vi.html"),
 "talbert_tactics": ("Talbert Tennis Tactics", "talbert_tennis_tactics_vi.html"),
 "how_to_play_winning": ("How to Play Winning Doubles", "how_to_play_winning_doubles_vi.html"),
 "modern_volley": ("Modern Tennis Volley Handbook 2026", "modern_tennis_volley_handbook_2026_vi.html"),
 "return_of_serve": ("Winning Doubles (Stan Smith)", "stan_smith_winning_doubles_vi.html"),
 "pattern_play": ("Pattern Play Tennis", "pattern_play_tennis_vi.html"),
 "competitive_tennis": ("Competitive Tennis (Schwartz)", "competitive_tennis_schwartz_vi.html"),
 "art_of_doubles": ("The Art of Doubles", "the_art_of_doubles_vi.html"),
 "doubles_strategy": ("Modern Doubles Strategy", "durr_doubles_strategy_vi.html"),
 "doubles_modern": ("Modern Tennis Doubles", "modern_tennis_doubles_vi.html"),
 "court_geometry": ("Court Geometry & Spatial Dynamics", "spatial_dynamics_tennis_vi.html"),
 "spatial_dynamics": ("Spatial Dynamics in Tennis", "spatial_dynamics_tennis_vi.html"),
 "mental_toughness": ("Mental Toughness in Tennis", "mental_toughness_tennis_vi.html"),
 "tennis_mind": ("Tennis and the Mind", "tennis_and_the_mind_vi.html"),
 "inner_game": ("The Inner Game of Tennis", "the_inner_game_of_tennis_vi.html"),
 "focused_tennis": ("Focused for Tennis", "focused_for_tennis_vi.html"),
 "visual_tennis": ("Visual Tennis Mental Imagery", "visual_tennis_mental_imagery_vi.html"),
 "tennis_confidential": ("Tennis Confidential", "tennis_confidential_vi.html"),
 "complete_conditioning": ("Complete Conditioning for Tennis", "complete_conditioning_for_tennis_vi.html"),
 "total_health": ("Total Health for Tennis", "total_health_tennis_vi.html"),
 "motor_learning": ("Motor Learning & Skill Acquisition", "science_of_coaching_tennis_vi.html"),
 "science_of_coaching": ("The Science of Coaching Tennis", "science_of_coaching_tennis_vi.html"),
 "coaching_tennis": ("Coaching Tennis Successfully", "coaching_tennis_successfully_vi.html"),
 "coaching_youth": ("Coaching Youth Tennis", "coaching_youth_tennis_vi.html"),
 "teaching_tennis": ("Teaching Tennis Volume 1", "teaching_tennis_volume_1_vi.html"),
 "tennis_drill": ("The Tennis Drill Book", "the_tennis_drill_book_vi.html"),
 "tennis_medicine": ("Tennis Medicine (Giacomo)", "tennis_medicine_giacomo_vi.html"),
 "rules_officiating": ("Official Rules & Officiating", "tennis_course_vi.html"),
 "stats_analytics": ("Match Statistics & Analytics", "high_tech_tennis_vi.html"),
}

terms = []
for (tid, en, vi, variants, cat, note, sources) in T:
    src = []
    for k in sources:
        if k in B:
            lbl, href = B[k]
            src.append({"label": lbl, "href": href})
    terms.append({
        "id": tid, "term_en": en, "term_vi_standard": vi,
        "variants_to_replace": variants, "category": cat,
        "note": note, "sources": src,
    })

data = {
    "title": "Từ Điển Thuật Ngữ Quần Vợt — Tennis Unified",
    "description": "Từ điển thuật ngữ và khái niệm quần vợt hiện đại, chuẩn hóa tiếng Việt, tổng hợp từ toàn bộ thư viện sách Tennis Unified.",
    "version": "2.0",
    "categories": C,
    "terms": terms,
}

here = os.path.dirname(os.path.abspath(__file__))
out = os.path.join(here, "tennis_glossary_vi.json")
with io.open(out, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=1)

# sanity
ids = [t["id"] for t in terms]
assert len(ids) == len(set(ids)), "duplicate ids: " + str([i for i in ids if ids.count(i) > 1])
print("terms:", len(terms))
from collections import Counter
for k, v in Counter(t["category"] for t in terms).items():
    print(f"  {k:24s} {v}")
print("wrote", out, os.path.getsize(out), "bytes")
